### ISSUE TITLE
`OutputContainer.add_stream` not properly documented

### ISSUE THREAD

**Issue by moi90** [PyAV-Org/PyAV#1004]
For `OutputContainer.add_stream` , only `codec_name` and `rate` are documented.

Descriptions are missing for `template`, `options` and `**kwargs`.

**Comment by jlaine** [comment]
A PR is welcome.

**Comment by moi90** [comment]
Please do not close.

**Comment by moi90** [comment]
> A PR is welcome.

There you are :)
