### ISSUE TITLE
Still can not use "torchvision.io.read_video" after install "av" by "pip install av"

### ISSUE THREAD

**Issue by BoopSainy** [PyAV-Org/PyAV#1006]
after I install av, there is still a error telling me 
"ImportError: PyAV is not installed, and is necessary for the video operations in torchvision.
See https://github.com/mikeboers/PyAV#installation for instructions on how to
install PyAV on your system."

How should I solve this problem?

ffmpeg: 4.3
torchvision: 0.13.0
av: 0.9.2

**Comment by uvjustin** [comment]
I'm guessing you mean av v9.2.0 and not v0.9.2.
Was there an error when you ran "pip install av"? What OS/architecture are you on?

**Comment by BoopSainy** [comment]
> I'm guessing you meant av v9.2.0 and not v0.9.2. Was there an error when you ran "pip install av"? What OS/architecture are you on?

Hi, I am using ubuntu 20.04. 

There is no error when ran "pip install av" and I could "import av" successfully now. But when I try to use "torchvision.io.read_video", I was told "PyAV is not installed"

**Comment by jlaine** [comment]
@BoopSainy if `import av` works there is nothing more we can do here, I'd suggest taking this up in the torchvision repository.

**Comment by BoopSainy** [comment]
> 

hi, I will try to figure this issue out later. Now I can just use opencv to load and save video for my project.

Thanks you a lot!
