### ISSUE TITLE
Demux generator does not see new data written to BytesIO buffer

### ISSUE THREAD

**Issue by robsmith11** [PyAV-Org/PyAV#1017]
**IMPORTANT:** Be sure to replace all template sections {{ like this }} or your issue may be discarded.

## Overview

It seems that only the data that's already in a BytesIO buffer when it's passed to `av.open` is able to be used by the demux generator.  When I write new bytes (from a live websocket fees) to the buffer, the demux generator doesn't see them.

## Expected behavior

New non-zero size packets are generated. 

## Actual behavior

The generated packets all have size zero. 

Traceback:
```
None
```

## Investigation

Googled 

## Reproduction

... 

## Versions

- OS: linux
- PyAV runtime:
```
Latest from pip
```
- PyAV build:
```
... 
```
- FFmpeg:
```
.. . 
```

## Research

I have done the following:

Googled

## Additional context

None

**Comment by jlaine** [comment]
Right, you are going to hit an end-of-file and demuxing will stop. How is PyAV supposed to know this BytesIO might receive data further down the line, and be notified? Maybe look into using a pipe instead.
