### ISSUE TITLE
Build wheels for Python 3.11

### ISSUE THREAD

**Issue by WyattBlue** [PyAV-Org/PyAV#1019]
Python3.11 just recently had its first release candidate available. https://www.python.org/downloads/release/python-3110rc1/

Both NumPy and Pillow already support 3.11, and now that the ABI is stable, it's the perfect time for PyAV to support 3.11 as well.

**Comment by papr** [comment]
+1 on this :)

**Comment by jlaine** [comment]
I don't think there is anything we need to do here, cibuildwheel (as of v2.10.0) should automatically build wheels for Python 3.11, so this will be covered as soon as we make our next release.

**Comment by papr** [comment]
Sounds great! Do you have an estimate for the next release date?

**Comment by jlaine** [comment]
I've tagged the release, expect wheels to reach PyPI in about 4 hours.

**Comment by papr** [comment]
Thank you!
