### ISSUE TITLE
Permission error when decode video

### ISSUE THREAD

**Issue by starsholic** [PyAV-Org/PyAV#1027]
## Overview
Permission error when decode video

## Actual behavior
Some videos encountered strange bugs like below
`video = av.open(path)`
`video.seek(0) # PermissionError: [Errno 1] Operation not permitted`
I've checked out the buggy video and everything seems normal. 

Traceback:
```
PermissionError: [Errno 1] Operation not permitted
```

## Reproduction

I use this code to extract video feature of the other dataset, the buggy video is [here](https://drive.google.com/file/d/1zSum-D_Oy0H6uFMHPixvDs2Wzs7Hv4kj/view?usp=sharing). 

![image](https://user-images.githubusercontent.com/52476332/189055141-370cecd5-c8ee-47f7-a102-2a262f70993a.png)

## Versions

- OS: linux and macos
- PyAV runtime:
```
PyAV v9.0.2
library configuration: --disable-static --enable-shared --libdir=/tmp/vendor/lib --prefix=/tmp/vendor --disable-doc --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-lzma --enable-version3 --enable-zlib
library license: GPL version 3 or later
libavcodec     58.134.100
libavdevice    58. 13.100
libavfilter     7.110.100
libavformat    58. 76.100
libavutil      56. 70.100
libswresample   3.  9.100
libswscale      5.  9.100
```

## Research

I have done the following:

googled

**Comment by jlaine** [comment]
You're going to have to dig further on your side, this seems specific to your local setup

**Comment by kevin1zc** [comment]
I got the exact same error. Do you have a workaround for it?

**Comment by coldeny** [comment]
Hello. Just wanted to say that I also experience the same issue and I use Windows. My file is not an AVI file. Should I open a seperate issue?
