### ISSUE TITLE
How do I capture a linux speakers output with av?

### ISSUE THREAD

**Issue by JaktensTid** [PyAV-Org/PyAV#1032]
Is this possible to capture ubuntu sound output using av.open?
I tried to pass default, name of device as the 'file input' parameter, but nothing works.
It just keeps saying me that 'File or directory does not exist'

Also tried `av.open(file='hw:0', format='alsa', mode='r')`
But it also says me, `no container format 'alsa'`

My os is ubuntu 20

**Comment by jlaine** [comment]
Currently the Linux binary wheels do not have ALSA support enabled as I have not found a way to do this in a portable way. See #941
