### ISSUE TITLE
Add stubs file to PyAV

### ISSUE THREAD

**Issue by RuoXian233** [PyAV-Org/PyAV#1065]
## Overview

There's currently **no .pyi files** in the PyAV installation path, which brings much difficulty to the development, a**s the language server 
couldn't resolve any symbols and provides no completion or hints.** 

## Desired Behavior

Add some basic stubs to PyAV, I'm not looking forward to a detailed type hint, just function signature and some documents,
I'd heard that there's some tools like _stubgen_ has the ability to finish the task automatically, but I'm not sure that it will work with Cython files and C module.  

## Additional context
I'll also try to write the stubs by myself, but I certainly need more help

**Comment by HanzCEO** [comment]
Hello @RuoXian233,

Would you like to draft a new PR and work on it? I would like to help.
