### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by ondave** [PyAV-Org/PyAV#1087]
Latest pip install version: 10.0.0

The documentation link here and on pypi point to:
https://pyav.org/docs/stable/ 
This appears to document version 9.0.2. Version 10.0.0 is not even an option.

**Comment by combs** [comment]
I just installed an 11.x via pip... I have no idea what's changed. The docs are dated 9.0.2. More recent versions are 9.1.0, 9.2.0, 10.0.0, 11.0.0. I have to assume that the two major dotreleases have changes, which might explain the new exceptions I'm seeing. Any chance we could get at least a changelog? <3

**Comment by WyattBlue** [comment]
You can see the docs here: https://pyav.basswood-io.com
