### ISSUE TITLE
How to compile pyav on platforms without available binaries. 

### ISSUE THREAD

**Issue by brentpicasso** [PyAV-Org/PyAV#1097]
## Overview
I have a need to build pyav on the raspberry pi platform, so I need to build pyav using ffmpeg sources.  What is the process for building? 

For building, do I need to have ffmpeg and libraries installed in a special way, such as with the --shared flag? 

There is a similar project, ffpyplayer, that has specific instructions on how to compile; it requires ffmpeg to be built with the --shared flag. 
https://matham.github.io/ffpyplayer/installation.html

If we can work through it here, I'll happily submit a PR to enhance the README for future users.  

Thanks!

**Comment by WyattBlue** [comment]
Did you look at the [Compile from Source Section](https://github.com/PyAV-Org/PyAV#alternative-installation-methods)?

**Comment by brentpicasso** [comment]
Yes - I initially tried that, but then realized I had some dependencies to install. I'll submit a PR to enhance the instructions. Got it installed successfully on the RPi.

Thanks for the quick help!

**Comment by brentpicasso** [comment]
https://github.com/PyAV-Org/PyAV/compare/main...brentpicasso:PyAV:patch-1
