### ISSUE TITLE
Where is the `av.bitstream ` now?

### ISSUE THREAD

**Issue by wqh17101** [PyAV-Org/PyAV#1100]
https://github.com/isarsoft/nvenc-h264-video-reader/blob/e8f109cc728daac4c06796223abb1046468820b5/GPUVideoReader.py#L7
I see an old code above. But i can not find  `av.bitstream ` in pyav 10.0.
So where is it now? What can i use what to replace it?

**Comment by mnuriyumusak** [comment]
any solution to this?
