### ISSUE TITLE
Why there is no ffmpeg binary library file in the WHL package I built?

### ISSUE THREAD

**Issue by shimachao** [PyAV-Org/PyAV#1104]
version: 8.10.0

I built pyav using the following command:
`source scripts/activate.sh /home/chao/FFmpeg`
`./scripts/build-deps`
`python setup.py bdist_wheel`

A whl file was generated，there is no ffmpeg binary library file in the WHL file. However, the whl file I downloaded from pypi contains the ffmpeg binary. so file, which is located in the av.libs directory.

Can anyone tell me how to package ffmpge related so files into whl ？

**Comment by shimachao** [comment]
auditwheel is greet

**Comment by ponponon** [comment]
> 

How do you do that? I want to know too
