### ISSUE TITLE
Feature Request: Support adding Frame side data.

### ISSUE THREAD

**Issue by anthornt** [PyAV-Org/PyAV#1153]
## Overview

I would like to be able to add side data to Frames. Specifically closed caption data (Type.A53_CC).

## Existing FFmpeg API

[av_frame_new_side_data()](https://ffmpeg.org/doxygen/trunk/group__lavu__frame.html#gae05843b941b79e56b955674e581a8262)

## Expected PyAV API

I would like to add side data to selected frames, for example by adding a new API Frame.side_data.add().

Example (modified examples/numpy/generate_video.py):
```
stream = container.add_stream("libx264", rate=fps)
...
for frame_i in range(total_frames):
    ...
    frame = av.VideoFrame.from_ndarray(img, format="rgb24")

    if (frame_i % fps) == 0:
        # Add closed caption
        data = bytearray()
        ...
        frame.side_data.add(data, Type.A53_CC)
```

## Investigation

I tried the attached patches to generate video with 608 style closed captions by modifying the generate video example.

I didn't manage to get the Frame.side_data updated correctly.

[20230817.0.patch](https://github.com/PyAV-Org/PyAV/files/12370551/20230817.0.patch)

**Comment by anthornt** [comment]
This patchset looks better:

[20230821.0.patch](https://github.com/PyAV-Org/PyAV/files/12394002/20230821.0.patch)

**Comment by WyattBlue** [comment]
I think given https://github.com/PyAV-Org/PyAV/pull/1249, we're going to do a one at a time approach for side data. For  closed caption data specifically I don't understand why you can't use a subtitle stream.
