### ISSUE TITLE
pyav gpu utilization

### ISSUE THREAD

**Issue by ncheng89** [PyAV-Org/PyAV#1156]
Hello, pyav development team. I've noticed that when using the GPU for encoding and decoding, pyav's utilization seems to be relatively low. In comparison, when I use the ffmpeg command, its GPU encoding utilization can reach 100%, and decoding is at 50%. However, with pyav, the encoding and decoding rates are only 30% and 20%, respectively. I truly appreciate pyav as an excellent open-source project and hope it can be further optimized. Attached is the relevant data chart.
![pyav-ffmpeg](https://github.com/PyAV-Org/PyAV/assets/48044818/b344468e-5bd7-40d2-8b56-b653642787e4)

**Comment by jlaine** [comment]
This has been debated to death in previous issues, and the docs explicitly state it's a non-goal.
