### ISSUE TITLE
Build wheels for Python 3.12

### ISSUE THREAD

**Issue by WyattBlue** [PyAV-Org/PyAV#1168]
Python3.12 is now released and the default choose for users who download python via [python.org](https://python.org)

I would also highly suggestion merging PR #1145 and #1110 so that building from source is a viable option.

**Comment by WyattBlue** [comment]
I'm closing this because I fixed this myself in my fork, [pyav](https://github.com/WyattBlue/pyav). You can switch by simply replacing `av` with `pyav` in your requirements or setup.py file.

I highly recommend everyone to switch because it's a bad idea to use a library that is not being maintained.

**Comment by WyattBlue** [comment]
All the necessary PRs are merged. The only step left is make release. @jlaine?

**Comment by jlaine** [comment]
I've tagged `v11.0.0`, in about 4 hours CI should upload the wheels to PyPI.

**Comment by WyattBlue** [comment]
It looks like we've hit the dreaded 10GB limit on PyPI. We should ask for an increase then redo the release.

```
  Project size too large. Limit for project 'av' total size is 10 GB. See
     https://pypi.org/help/#project-size-limit    
```

**Comment by jlaine** [comment]
Yup we should, except I don't own the project, so I can't clean up old releases or reach out to PyPI.

 @mikeboers ?

**Comment by jlaine** [comment]
I have tried deleting the wheels of two releases (8.0 and 8.0.1) but I'm still getting the "project too large" error.. Let's hope PyPI support raises the limit.

**Comment by jlaine** [comment]
I deleted even more files and this time the upload went through. We'll be stuck again at the next release though..

**Comment by waclaw66** [comment]
Could you please provide wheels for Python 3.12?
There is still Python 3.11 version only https://pypi.org/project/ha-av/#history

**Comment by WyattBlue** [comment]
> Could you please provide wheels for Python 3.12? There is still Python 3.11 version only https://pypi.org/project/ha-av/#history

We don't control that namespace

**Comment by waclaw66** [comment]
> > Could you please provide wheels for Python 3.12? There is still Python 3.11 version only https://pypi.org/project/ha-av/#history
> 
> We don't control that namespace

Thanks for explanation, there is URL leading to this project. Maybe it's a fork.

**Comment by niksirbi** [comment]
Thanks a lot @WyattBlue and @jlaine for solving this issue! Your work is highly appreciated ❤️ 

I was wondering if you are also planning to update the `conda-forge` releases of `av` accordingly. As far as I can tell, the latest version on `conda-forge` is 11.0. Or perhaps the `conda-forge` feedstock of `av` is maintained independently? 

Apologies if this is not the right place to ask.
