### ISSUE TITLE
Add support for begin, end offset to open

### ISSUE THREAD

**Issue by tchaton** [PyAV-Org/PyAV#1170]
Hey there,

Thanks a lot for this library. I am working on making training deep learning model in the cloud fast and efficient.

A common approach to do so is to binarise or tar files into a single chunk. However, when reading the data back, it can become challenging if the readers don't support either directly bytes or begin, end offsets.  

I wonder if it would be possible to add support for such things to enable training videos in the cloud fast.

As a way around, libraries are writing down bytes to the disk and reading it back leading to performance loss and reduce disk space: https://github.com/webdataset/webdataset/blob/main/webdataset/autodecode.py#L400

**Comment by WyattBlue** [comment]
I'm going to say no. The ffmpeg libraries don't appear to support this, and frankly this use case seems very niche.

You may find [this](https://stackoverflow.com/questions/30807507/is-there-a-byte-offset-in-ffmpeg-for-source-files) interesting, but beyond that, you're not going to get any more support from this group of unpaid volunteers.

**Comment by tchaton** [comment]
Hey @WyattBlue,

That's totally understandable. Thanks for replying me. 

Best regards,
T.C
