### ISSUE TITLE
Allow direct creation of AudioFrame with planes data

### ISSUE THREAD

**Issue by daveisfera** [PyAV-Org/PyAV#1172]
## Overview

Currently, an `AudioFrame` has to be created and then the data set after the fact ( [see here](https://github.com/PyAV-Org/PyAV/blob/6982d818080716b39bc3f333cf19daa0a3e0b56a/av/audio/frame.pyx#L129) ), but it would be nice to be able to set the `planes` directly

## Desired Behavior

Ability to set `array` or `planes` in the `AudioFrame` init

## Example API

Then the linked to code could be replaced with:
```
return AudioFrame(array=array, format=format, layout=layout, samples=samples)
```

**Comment by jlaine** [comment]
I don't really have plans for this, the API is already complex enough.
