### ISSUE TITLE
'libav.pxd' not found when using cimport in Cython

### ISSUE THREAD

**Issue by ElinLiu0** [PyAV-Org/PyAV#1176]
Hi,i'm gonna trying to use av library in Cython,which to build a faster FrameProcessor component of my Yolo APP.
Yet,when i run setup.py,it raised error like below:
```shell
Compiling FrameProcessor.pyx because it changed.
[1/1] Cythonizing FrameProcessor.pyx
D:\Anaconda\envs\edge\lib\site-packages\Cython\Compiler\Main.py:384: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: D:\My Code\StudentBehaviorDetection\components\Cythonize\FrameProcessor.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)

Error compiling Cython file:
------------------------------------------------------------
...
from libc.stdint cimport int16_t, int32_t, uint8_t, uint16_t, uint64_t
cimport libav as lib
        ^
------------------------------------------------------------

D:\Anaconda\envs\edge\lib\site-packages\av\video\frame.pxd:2:8: 'libav.pxd' not found
```
Is there any solve ?

**Comment by WyattBlue** [comment]
How exactly are you building PyAV? Also you should try building from `main` because we've made a lot of important changes that making building easier.

**Comment by ElinLiu0** [comment]
> How exactly are you building PyAV? Also you should try building from `main` because we've made a lot of important changes that making building easier.

Well,i compiled it successfully after three days post this issue,yet it still have some issue of data typing while using dnn to inference,that's too complex to me so i gave up😂.
