### ISSUE TITLE
Allow `pathlib.Path` object in `av.open()`

### ISSUE THREAD

**Issue by v-iashin** [PyAV-Org/PyAV#1181]
## Overview

`av` fails when `pathlib.Path` object is provided with `ValueError`.

MWE:
```python
import av
from pathlib import Path
# works
container = av.open('file.mp4')
# fails
container = av.open(Path('file.mp4'))
```

## Desired Behavior

I don't want to bother casting the path variable to `str`.

## Example API

```python
container = av.open(Path('file.mp4'))
```
should work.

**Comment by jlaine** [comment]
Sure, a PR for this is welcome.
