### ISSUE TITLE
Detect attempted use of static libraries, and abort

### ISSUE THREAD

**Issue by mikeboers** [PyAV-Org/PyAV#120]
We cannot use static FFmpeg/Libav, so we should throw up an error if we can detect that.

**Comment by jlaine** [comment]
I'm not sure I agree with this issue : why would using a static build of FFmpeg be an issue per se?

AFAICT the problem is we are trying to be smart about parsing CFLAGS / LDFLAGS from pkg-config without passing `--static` to pkg-config:

```bash
$ pkg-config --libs libavcodec
-lavcodec

$ pkg-config --static --libs libavcodec
-lavcodec -lvpx -lm -lvpx -lm -lvpx -lm -lvpx -lm -lwebpmux -lwebp -lm -llzma -lcrystalhd -lrsvg-2 -lm -lgio-2.0 -lgdk_pixbuf-2.0 -lgobject-2.0 -lglib-2.0 -lcairo -lzvbi -lm -lpthread -lm -lpng -lz -lsnappy -lstdc++ -lz -laom -lm -lpthread -lcodec2 -lgsm -lmp3lame -lm -lopenjp2 -lopus -lm -lshine -lspeex -ltheoraenc -ltheoradec -logg -ltwolame -lvorbis -lvorbisenc -lwavpack -lwebp -lx264 -lx265 -lxvidcore -ldl -pthread -lva -lswresample -lm -lsoxr -lavutil -pthread -lva -lva-drm -lva -lva-x11 -lX11 -lvdpau -lX11 -lm -ldrm -lva
```

**Comment by mikeboers** [comment]
I don't have an issue with it in principal, but the most common build failure at this point is because it tries to link against static ones.

I'd be happy to have it do whatever, but at this point static results in failure.

My gut says that static won't work as soon as there is any state in the library at all. I couldn't do that with [PyTomCrypt](https://github.com/mikeboers/pytomcrypt). I'd be keen to see though.
