### ISSUE TITLE
On Gitter

### ISSUE THREAD

**Issue by WyattBlue** [PyAV-Org/PyAV#1216]
Who controls https://gitter.im/PyAV-Org?
Who controls the server?

Linking to a 404 error is not a great look for us. If we can't restore this, say December 10, we should remove references to it.

**Comment by jlaine** [comment]
It looks like sometime around February 2023 gitter.im fully integrated with Matrix, which changed the URLs:

https://app.gitter.im/#/room/#PyAV-Org_User-Help:gitter.im

**Comment by WyattBlue** [comment]
Thanks. I've changed all the references so it points to the actual room.
