### ISSUE TITLE
Unable to perform code signing on .dll files in av.libs

### ISSUE THREAD

**Issue by ArminHaberl** [PyAV-Org/PyAV#1223]
Dear maintainers of pyAV,

we are currently using pyAV in our audio transcription software 'aTrain'[(GitHub)](https://github.com/BANDAS-Center/aTrain/tree/main/aTrain). To properly distribute the app and provide trust in our code we need to perform code signing.

We use [SignTool.exe](https://learn.microsoft.com/de-de/dotnet/framework/tools/signtool-exe) from the [.NET Framework-Tools](https://learn.microsoft.com/de-de/dotnet/framework/tools/) to perform said code signing on Windows.
It is possible for us to sign every code and all .dll-files in our project except the .dll-files in pyAV's av.libs directory.

We tried to sign these .dll-file with a command similar to this one:
` signtool sign /a /fd SHA256 <PATH TO LIBRARY>\av.libs\avcodec-59-6fa00e8c4c19c8b4920003b2eb5d54f7.dll`

Unfortunately, we get the following error:
```
Done Adding Additional Store
SignTool Error: SignedCode::Sign returned error: 0x800700C1
        For more information, please see https://aka.ms/badexeformat
SignTool Error: An error occurred while attempting to sign: venv\Lib\site-packages\av.libs\avcodec-59-6fa00e8c4c19c8b4920003b2eb5d54f7.dll

Number of errors: 1
```

This error **only occurs** when signing **.dll-files in av.libs**, all other .dll-files contained in other libraries of the project are possible to sign without errors. 

My environment is as follows:
- Operation System: Windows 11 Pro, Version 22H2
- Python Version:  3.11.5
- Version of pyAV: 10.0.0
- singtool version as provided in the Windows 11 SDK (10.0.22621.0)

I already tried to find a solution by myself and encountered two possible reasons for the problem:

- The dll-files are already signed and signtool therefore cannot sign them again. [(see here)](https://markcz.wordpress.com/2013/01/26/signtool-exe-returned-error-0x800700c1/)
I tried to remove possible existing code signatures even though I could not find signatures in the first place.
This **did not fix** the problem.

- The dll-files have faulty PE headers[ (see here)](https://techcommunity.microsoft.com/t5/msix/signtool-error-signedcode-sign-returned-error-0x800700c1/m-p/857595)
I could not find a proper solution to a problem with PE headers, since my knowledge of this matter is very limited. 

I would be happy if you could direct me in a possible direction to resolve this issue.

Best regards,
Armin

**Comment by WyattBlue** [comment]
We just provide the source code and the ffmpeg binaries we build in an unspecial way. You should talk to someone who specializes in Windows signing.
