### ISSUE TITLE
codec parsing failed first

### ISSUE THREAD

**Issue by autoDR** [PyAV-Org/PyAV#1261]
## Overview

Create codec by av.CodecContext.create('hevc', 'r'), The result is empty execution time execute 
packets = codec.parse(video_bytes)

## Expected behavior

The resolution succeeds after the second attempt

## Actual behavior
![20240115-203922](https://github.com/PyAV-Org/PyAV/assets/70084835/446be539-f599-4805-b9ed-0555cd0ec89e)

## Versions

- OS: ubuntu 20.4
- PyAV runtime:12.0.2

**Comment by WyattBlue** [comment]
See #1262
