### ISSUE TITLE
codec parsing failed first

### ISSUE THREAD

**Issue by autoDR** [PyAV-Org/PyAV#1263]
Overview
Create codec by av.CodecContext.create('hevc', 'r'), The result is empty execution time execute
packets = codec.parse(video_bytes)

Expected behavior
The resolution succeeds after the second attempt

Actual behavior
20240115-203922

Versions
OS: ubuntu 20.4
PyAV: runtime:12.0.2
python: 3.10.9

**Comment by autoDR** [comment]
![image](https://github.com/PyAV-Org/PyAV/assets/70084835/03629a52-8226-4870-9108-e32dc03db725)

**Comment by WyattBlue** [comment]
You need to install PyAV with `pip install av`, not `pip install pyav`. The version you installed doesn't have hevc compiled in. 

Also please use text like this instead of images:
```python
import sys
import av

f_w = open("hevc_test.h265", "br")
video_bytes = f_w.read()
codec = av.CodecContext.create("hevc", "r")
packets = codec.parse(video_bytes)
for packet in packets:
    for frame in codec.decode(packet):
        if isinstance(frame, av.VideoFrame):
            image = frame.to_image()
            image.save(f"demo.jpg")
            sys.exit()
```

**Comment by autoDR** [comment]
thanks
I uninstall pyav and install with `pip install av`  , But the problem that couldn't be solved the first time remains
![20240123151342_rec_](https://github.com/PyAV-Org/PyAV/assets/70084835/f8c58c9b-6fe5-4921-9edd-840eff60637e)
