### ISSUE TITLE
Update some documentation links

### ISSUE THREAD

**Issue by jasper-tms** [PyAV-Org/PyAV#1363]
I see in #1248 that the doc links have been moved from pyav.org to pyav.basswood-io.com in a number of places, but the old link is still around in at least two places that I see:
- [ ] The top right corner of https://github.com/PyAV-Org/PyAV which is the website listed in the repo metadata.
- [ ] The documentation link on https://pypi.org/project/av/, which comes from setup.py [here](https://github.com/PyAV-Org/PyAV/blob/1b27fc96ff3d1dc9eb7774f065a5e8e9c43475d8/setup.py#L197)

It's a shame that the doc hosting had to move! No chance for getting pyav.org back? Any chance it could be taken down and just redirect to the new site?

**Comment by WyattBlue** [comment]
Mike Boers controls the pyav.org domain. I don't know if he wants to make it active again or archive it.

Boers and jlaine have admin permission so they could change the url at the top if they want

**Comment by WyattBlue** [comment]
@mikeboers @jlaine Can you change the url on the GitHub to https://pyav.basswood-io.com. People are getting confused when they're being served old docs.

**Comment by jlaine** [comment]
I've changed the link as requested.

Do you think it would be possible to use `readthedocs` as using a custom domain is going to pose the same problem of being linked to one maintainer as `pyav.org` did? Or is the docs build process still too intricate?

**Comment by WyattBlue** [comment]
It wouldn't be impossible.

**Comment by WyattBlue** [comment]
Closing sense we've changed both locations OP mentioned with an up to date docs.
