### ISSUE TITLE
Building whl files

### ISSUE THREAD

**Issue by FanofVS** [PyAV-Org/PyAV#1365]
### Discussed in https://github.com/PyAV-Org/PyAV/discussions/1361

<div type='discussions-op-text'>

<sup>Originally posted by **FanofVS** April  1, 2024</sup>
After running command 'pip install av', we can find that a whl file is downloaded, and pyav is installed by extracting it.
![截屏2024-04-01 下午5 39 53](https://github.com/PyAV-Org/PyAV/assets/43821502/bccb409f-833b-4b78-b5d7-0c46c6430c4f)
As we can see, the installation is like this:
![截屏2024-04-01 下午5 42 40](https://github.com/PyAV-Org/PyAV/assets/43821502/47d192e9-c144-4fa0-b9f3-8cd66595b6a3)
I would like to know how to build such a whl file that contains all depended libraries(in the pic above, the ffmpeg libraries under the directory 'av.libs'), so that I can build one with my own ffmpeg version
</div>

**Comment by WyattBlue** [comment]
This should only be a discussion, not an issue.
