### ISSUE TITLE
Build wheel use my own ffmpeg, but can't find the av.libs path.

### ISSUE THREAD

**Issue by vonsago** [PyAV-Org/PyAV#1366]
```
# here is my building steps

PYAV_LIBRARY=/path/my/ffmpeg/ source scripts/activate.sh
./scripts/build-dep 
python3 setup.py bdist_wheel
```

the I get the diff between mybuildav.wheel and the av.8.0.3.wheel

normal av.8.0.3 wheel file
![image](https://github.com/PyAV-Org/PyAV/assets/22726829/8eb3d376-869c-4a20-9ae0-99270eaa260e)

here is my wheel.
![image](https://github.com/PyAV-Org/PyAV/assets/22726829/e9b61388-7dc1-42fe-a83c-40e6175b9a46)
the wheel file I built miss av.libs path. I wanna know why the wheel file I built miss the av.libs and how to fix it.

**Comment by WyattBlue** [comment]
I don't think anyone in the world knows how to build av 8.x.x anymore.
