### ISSUE TITLE
frame.index is deprecated

### ISSUE THREAD

**Issue by YoniChechik** [PyAV-Org/PyAV#1392]
https://github.com/PyAV-Org/PyAV/commit/17e86d152ff3b13427f29a457824b6227d210f6d
This is the commit that deprecated frame.index.
currently in v12.0 we get this warning, but nothing about how to fix it...

even in the site's main page we have a usage of this frame.index:

https://pyav.org/docs/stable/index.html#basic-demo
```
import av

container = av.open(path_to_video)

for frame in container.decode(video=0):
    frame.to_image().save('frame-%04d.jpg' % frame.index)
```

What is the alternative?

**Comment by WyattBlue** [comment]
The alternative is to use `enumerate` [as shown](https://pyav.basswood-io.com) in the new docs website
