### ISSUE TITLE
Provide Apple M1 binaries for pypy

### ISSUE THREAD

**Issue by FirefoxMetzger** [PyAV-Org/PyAV#1394]
While doing some changes in ImageIO I've noticed that our test suite started to fail because it lacks pre-compiled pyav binaries for MacOS on pypy. I suspect that this is because `macos-latest` runners now use M1 ([xref](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories)) which also breaks our test suite for FreeImage tests in a different place.

Would it be possible to add builds for this chipset to the build matrix?

**Comment by WyattBlue** [comment]
Pypy requires the host to be Apple Silicon in order to build Apple Silicon wheels.

[from here](https://github.com/PyAV-Org/PyAV/actions/runs/8858368719/job/24326921109)
>Note: pp39-macosx_arm64, pp310-macosx_arm64 were selected, but can't be built on x86_64 so will be skipped automatically.

**Comment by WyattBlue** [comment]
Done. https://github.com/PyAV-Org/PyAV/pull/1395
