### ISSUE TITLE
Failing to decode audio with manually created audio decoder

### ISSUE THREAD

**Issue by caliangxie** [PyAV-Org/PyAV#1470]
## Overview
I am trying to decode audio packets from a Hikvision camera stream using a `AudioCodecContext` that was created outside the input container.

I need to manually create the audio decoder as I am sending the packets to another process and I need to decode the packets there instead. I was planning on sending over the parameters of the original decoder and recreating the decoder with those parameters.

## Expected behavior
I expect the decoding to proceed successfully.

## Actual behavior
An internal BugError is thrown.

Traceback:
```
Traceback (most recent call last):
  File "/tmp/test.py", line 14, in <module>
    for frame in new_cc.decode(packet):
  File "av/codec/context.pyx", line 450, in av.codec.context.CodecContext.decode
  File "av/codec/context.pyx", line 465, in av.codec.context.CodecContext.decode
  File "av/codec/context.pyx", line 366, in av.codec.context.CodecContext._send_packet_and_recv
  File "av/codec/context.pyx", line 390, in av.codec.context.CodecContext._recv_frame
  File "av/error.pyx", line 326, in av.error.err_check
av.error.BugError: [Errno 558323010] Internal bug, should not have happened
```

## Reproduction
```python
import av
from av.audio.format import AudioFormat

container = av.open('./video.avi')

audio_stream = container.streams.audio[0]
original_cc = audio_stream.codec_context
new_cc = av.Codec(original_cc.name).create()
new_cc.format = AudioFormat(original_cc.format.name)
layout = av.AudioLayout(original_cc.layout.name)
new_cc.layout = layout

for packet in container.demux(audio=0):
    for frame in new_cc.decode(packet):
        print('decoded', frame)
```
A sample video is placed in the zip that is attached to this issue.

## Versions

- OS: Ubuntu 22.04.4 LTS
- PyAV runtime:
```
PyAV v12.3.0
library configuration: --disable-static --enable-shared --libdir=/tmp/vendor/lib --prefix=/tmp/vendor --disable-alsa --disable-doc --disable-libtheora --disable-mediafoundation --enable-fontconfig --enable-gmp --enable-gnutls --enable-libaom --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libspeex --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libxml2 --enable-lzma --enable-zlib --enable-version3 --enable-libx264 --disable-libopenh264 --enable-libx265 --enable-gpl
library license: GPL version 3 or later
libavcodec     60. 31.102
libavdevice    60.  3.100
libavfilter     9. 12.100
libavformat    60. 16.100
libavutil      58. 29.100
libswresample   4. 12.100
libswscale      7.  5.100
```

## Research

I have done the following:

- [x] Checked the [PyAV documentation](https://pyav.basswood-io.com)
- [x] Searched on [Google](https://www.google.com/search?q=pyav+erno+558323010)
- [x] Looked through [old GitHub issues](https://github.com/PyAV-Org/PyAV/issues?&q=is%3Aissue)

## Additional context
The camera is a Hikvision DS-2CD2443G0-I(W) that is using the following parameters for the codecs:
Audio:
- PCM MU-LAW
- Mono
- 8000 Hz
- 16 bits per sample
Video:
- H264
- 1920x1080
- 25 fps
[video.zip](https://github.com/user-attachments/files/16376893/video.zip)

**Comment by WyattBlue** [comment]
> I need to manually create the audio decoder as I am sending the packets to another process

No no no no no no. This is not how this works. This is not how any of this works. Decoding packets depends on the original container and decoder. Your `new_cc` variable could never decode packets correctly because of how ffmpeg works.
