### ISSUE TITLE
PyAV Incorrect Decoding of QuickTime Video

### ISSUE THREAD

**Issue by hnhuang** [PyAV-Org/PyAV#1477]
PyAV (version 12.3.0) decodes QuickTime videos incorrectly, resulting in the color appearing with too much exposure. This issue affects the visual quality and accuracy of the decoded video.

My code to decode the QuickTime videos:

`
count = 0
for fn in movieLists:
    print('Now processing: ', fn)
    try:
        container = av.open(fn)
    except Exception as e: 
        print(e)
        continue

    rotateCode = check_rotation(container.streams.video[0].metadata)
    print("rotate code = ", rotateCode)

    frames = container.decode(video=0)
   
    for frame in frames:
        image = frame.to_image()
        if rotateCode is not None:
            image = image.transpose(method=rotateCode)

        image.save(imageFolder + '/' + str(count) + '.jpg')
        count += 1
`
One of the images I obtain:

![20](https://github.com/user-attachments/assets/44701dc2-e5e2-462e-be48-984e58969cd1)

But it should be like this one:

![20](https://github.com/user-attachments/assets/d52d8b49-85ea-413a-b831-645612bd5d14)

**Comment by WyattBlue** [comment]
```python
image = frame.to_image()
```
The Pillow library is the one actually changing the color space here.
