### ISSUE TITLE
Support `av_find_best_stream`

### ISSUE THREAD

**Issue by rectalogic** [PyAV-Org/PyAV#1481]
## Overview

Add support for [`av_find_best_stream`](https://ffmpeg.org/doxygen/trunk/group__lavf__decoding.html#ga757780d38f482deb4d809c6c521fbcc2) to [StreamContainer](https://pyav.org/docs/stable/api/stream.html#av.container.streams.StreamContainer)

## Desired Behavior

Using the C libav APIs I would usually first find the "best" video stream, and then find the "best" related audio stream:
```c
int video_stream_index = av_find_best_stream(format_context, AVMEDIA_TYPE_VIDEO, -1, -1, &video_codec, 0);
int audio_stream_index = av_find_best_stream(format_context, AVMEDIA_TYPE_AUDIO, -1, video_stream_index, &audio_codec, 0);
```

## Example API

[StreamContainer.get](https://pyav.org/docs/stable/api/stream.html#av.container.streams.StreamContainer.get) is pretty overloaded, maybe a new API like `StreamContainer.best(type: str, related: Stream | None) -> Stream` where `type` is [Stream.type](https://pyav.org/docs/stable/api/stream.html#av.stream.Stream.type) ?

**Comment by moonsikpark** [comment]
makes sense to me
