### ISSUE TITLE
pyav.org is outdated, points to 9.0.2

### ISSUE THREAD

**Issue by mic47** [PyAV-Org/PyAV#1574]
This website https://pyav.org/docs/stable/ is not updated, it has version 9.0.2 and not 13.1.0 (like it's on https://pyav.basswood-io.com/docs/stable/ ). I find it via google (top google link when searching for pyav), and using it caused issues while installing library (I pinned version, which was obviously old). I wasted maybe an hour until I figured it out :-) Thanks

**Comment by WyattBlue** [comment]
@mikeboers controls pyav.org but he isn't active anymore.
We've changed the link everywhere we could.

**Comment by dotysan** [comment]
Has anyone attempted to reach out to him? He's got loads of contact/company info on his site.

**Comment by dotysan** [comment]
```
Domain Name: pyav.org
Creation Date: 2020-04-30T13:49:41Z
Registry Expiry Date: 2025-04-30T13:49:41Z
```

**Comment by mic47** [comment]
I tried to email him after this issue got closed, so far no response (I used inquiry email on his website).
