### ISSUE TITLE
MP4 file missing in example

### ISSUE THREAD

**Issue by AlkisPis** [PyAV-Org/PyAV#1604]
In the example https://github.com/PyAV-Org/PyAV/blob/main/examples/basics/save_keyframes.py the file 
'pexels/time-lapse-video-of-night-sky-857195.mp4' is missing from the package
At least, say where one can find it. Or use "yourfile.mp4" as filename  to indicate that any MP4 file will do.
Common sense, man, Common sense. And a little less programming carelessness.

**Comment by WyattBlue** [comment]
That file is hosted online. The function will automatically get it.
