### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by AlkisPis** [PyAV-Org/PyAV#1608]
In the example at https://github.com/PyAV-Org/PyAV/blob/main/examples/subtitles/remux.py the file  **webvtt.mkv** is not found. No mention where to find it either. How can this script run? What does this file contain? Why is it used?

What's with you people? Why such a  sloppiness? What's the meaning or usefulness of publishing a non-runnable code from which also vital documentation/information is missing?

**Comment by WyattBlue** [comment]
The `resources/webvtt.mkv` is a stand-in for any mkv file with a webvtt subtitle stream. Since this is an example file, and not library or testing code, an actual webvtt.mkv is not provided. Please keep it civil when discussing the project.

**Comment by AlkisPis** [comment]
Thank you for your reply. How could I --or someone else--  one know this about this 'resources/webvtt.mkv' stuff? Really, think about it: Because the coder knows about it, it doesn't mean that everyone else knows too. What does it cost to the coder to write a short comment about it? So, is it **me** who must apologize for my "uncivil" message, in which **all the questions in it are valid**?

BTW, this is not lack of civileness. I didn't talk badly. It is a protest coming from my long experience with coders' and documenters' repetitive sloppiness. I am a progammer, coder and documenter and when I post any code in the Web I always use comments, even for things that are much more obvious than the above case. Ask me why.

(Note: Before this post, I used a civil "please", but it did not have any effect. I didn't reveive any reply.  My (superficial) "uncivileness" though had an effect.  Thank you.)

**Comment by WyattBlue** [comment]
Regardless of "correctness", such provocative and emotional language (in both this issue and the first) directed at a contributor is not acceptable. If it was directed at a random person, you would have already been banned.

**Comment by AlkisPis** [comment]
I undestand what you say and I respect it. (Well, to a certain point, of course. E.g. I can't take "banning" seriously in the specific case.) 
But what amazes me however is that you didn't addreess --on a second plane-- **any of the problems** I mentioned and whether I was right or wrong. 
Consider also that this same code has a **real bug** that I reported in a next Issue that I submitted and which you didn't even deign to address it all. Really What you could you expect from me to say about all that? 

BTW, being a contributor --I am one myself in varilous forums and communities-- does not mean that you can post problematic code and/or not expect or even ignore problems that users are reporting. 
In my experience, normally programmers thank users for reporting problems because only in that way they can correct them and become better themselves. You, instead, are annoyed. 

I hope that someday all I'm trying to communicate to you in here will be very clear and real to you. Have a nice day.
