### ISSUE TITLE
Convenience Frame.load/save methods

### ISSUE THREAD

**Issue by mikeboers** [PyAV-Org/PyAV#161]
Implement these with FFmpeg instead of PIL (e.g. via `frame.to_image().save(path)`).

**Comment by TechWhizZ199** [comment]
Just out of curiosity will this allow us to use methods such as avcodec_decode_video2 methods? Or has that already been implemented elsewhere?

**Comment by mikeboers** [comment]
@TechWhizZ199: Encoding/decoding without a container is #155. Otherwise, we do decode [via that function](https://github.com/mikeboers/PyAV/blob/master/av/video/stream.pyx#L50) already.

**Comment by TechWhizZ199** [comment]
Oh I see. Thank you!

**Comment by jlaine** [comment]
I'm not sure this ticket makes sense, it doesn't feel as though it's PyAV's job

**Comment by mikeboers** [comment]
It isn't the job, no, but I feel like it would be handy enough.

I personally have a lot of silly round-trips through Pillow just for loading and saving images. FFmpeg understands those, and we could use that machinery.

They would be pretty short methods. I just threw together [this one](https://github.com/mikeboers/PyAV/blob/frame_save/av/video/frame.pyx#L304-L339).
