### ISSUE TITLE
Document new-style stream selection

### ISSUE THREAD

**Issue by ReaddyEddy** [PyAV-Org/PyAV#187]
Python3.5 requires replacing 
video = next(s for s in container.streams if s.type == b'video')
with 
video = next(s for s in container.streams.video):

As I work through the rest of the examples I'll clone the repo and create a pull request if I find more issues.

**Comment by mikeboers** [comment]
Hi @ReaddyEddy!

I don't think Python3 *requires* such a change, but switching to the new-style stream selection in the examples/docs should be done.

Either of `container.streams.get(video=0)` or `container.streams.video[0]` should do (IIRC).

**Comment by ReaddyEddy** [comment]
I'll check your suggestion in 3.5.2_1 which was the version that showed the issue for me, without any references to import future etc.
