### ISSUE TITLE
Subtitle stream encode method

### ISSUE THREAD

**Issue by pohmelie** [PyAV-Org/PyAV#196]
Is it possible to build embedded subtitles with `PyAV`? I don't see `encode` method of `SubtitleStream`. And I don't understand how to construct subtitles "frame".

**Comment by MarSoft** [comment]
Second this. For me it looks like this library does not support encoding subtitles... Not sure if it is supported in the libav at all.

**Comment by MarSoft** [comment]
Some information is available here: https://lists.ffmpeg.org/pipermail/libav-user/2013-September/005548.html
But I don't think it will help :-(

**Comment by pohmelie** [comment]
Don't close 😭

**Comment by pohmelie** [comment]
Nasty bot!

**Comment by jlaine** [comment]
Does anyone plan to submit a PR for this?
