### ISSUE TITLE
Magically find exactly the requested non-key frame when seeking

### ISSUE THREAD

**Issue by mikeboers** [PyAV-Org/PyAV#210]
This is the sort of thing you need to do when you want a precise (non-key) frame:

```
fh = av.open(args.movie)

video = fh.streams.video[0]

def iter_frames():
    for packet in fh.demux(video):
        for frame in packet.decode():
            yield frame

for i in xrange(100):

    pts = fh.duration * i / 100
    time_ = pts / float(av.time_base)

    fh.seek(pts)
    
    for j, frame in enumerate(iter_frames()):
        if j > 100:
            print 'Did not find target within 100 frames of seek.'
            break
        if frame.pts * frame.time_base >= time_:
            print 'Found target in', j, 'frames.'
            break

   # Do something with frame.

```

This should be done by default, and disabled by `bare_bones=True` (or whatever #209 decides).

**Comment by caspervdw** [comment]
I have encountered this issue too implementing a PyAV wrapper in PIMS:

https://github.com/soft-matter/pims/blob/master/pims/pyav_reader.py#L70

Including this seeking functionality within PyAV would be a great way to go. However, to me one of the advantages of using PyAV is exactly this "bare_bones" access into ffmpeg, which makes it really fast and also understandable from a ffmpeg point of view.

Personally, I would add all the "costly" magic (like this one) in a different class that is derived from the bare-bones ffmpeg interface. In that way, the distinction between "bare bones" and "magic" would be more clear, and also the flexibility in the API would be greater.

**Comment by jonahpearl** [comment]
Hi there -- is this still the preferred way to find a precise non-key-frame in pyav? Acc to the docs, it looks like the `use_magic` type options never got implemented. Thanks!
