### ISSUE TITLE
Memory leak in filter graph push/pull

### ISSUE THREAD

**Issue by s-zeid** [PyAV-Org/PyAV#215]
Hi, I'm trying to set up a filter graph for a video stream and I'm seeing some pretty serious leaks:  frames from a ~1m45s long, 30 FPS, 640x480 video as input result in 1353652 kB (~1GB) of memory usage in my test case (in which the only filter is fps=fps=60).  30 seconds of a 1080p 25 FPS video result in 2309280 kB (~2GB) of memory usage.

**Test case:**
Script (offending code is in `leak()`):  <https://gist.github.com/scottywz/9a5177850f49147fcd5019770c1ff534>
Video 1:  <https://uploads.s.zeid.me/pyav-issue-215/tyt-rap.cropped.qh3gfqHM5Mo.mp4>
Video 2:  <https://uploads.s.zeid.me/pyav-issue-215/einaudi-elegy-30s.2DLnhdnSUVs.mp4>

Transcript (and I do get the same results when the files are local):  
```sh
$ ./filter-leak.py 'https://uploads.s.zeid.me/pyav-issue-215/tyt-rap.cropped.qh3gfqHM5Mo.mp4' 1
*** DONE: 1 iteration, 3076 frames ***
*** Memory usage from run: 1363260 kB (~1GB) ***
Press Enter to exit

$ ./filter-leak.py 'https://uploads.s.zeid.me/pyav-issue-215/einaudi-elegy-30s.2DLnhdnSUVs.mp4' 1
100 buffers queued in buffersink, something may be wrong.
*** DONE: 1 iteration, 750 frames ***
*** Memory usage from run: 2309280 kB (~2GB) ***
Press Enter to exit
```

Note:  It seems like the memory usage corresponds to the memory used by the decoded input frames, not the memory used by frames in the buffersink.  To use the second video as an example:  750 frames * 12 bits per pixel (yuv420p) * 1920 * 1080 / 8 bits/byte / 1024 kB/B = 2278125, which is close to the memory usage reported by the test script.  The filter doubles the framerate (i.e. outputs 1500 frames instead of 750), so if the output frames were being leaked, the usage ought to be double.

**System info:**
PyAV 0.3.3 from PyPI
Python 3.5.3 from distro
Fedora 25 x86_64
ffmpeg-libs 3.1.7-1.fc25.x86_64

`/usr/bin/ffmpeg -version`:
```
ffmpeg version 3.1.7 Copyright (c) 2000-2017 the FFmpeg developers
built with gcc 6.3.1 (GCC) 20161221 (Red Hat 6.3.1-1)
configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic' --extra-ldflags='-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld' --enable-bzlib --disable-crystalhd --enable-fontconfig --enable-frei0r --enable-gcrypt --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libcdio --enable-indev=jack --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmp3lame --enable-nvenc --extra-cflags=-I/usr/include/nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-x11grab --enable-avfilter --enable-avresample --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-libmfx --enable-runtime-cpudetect
libavutil      55. 28.100 / 55. 28.100
libavcodec     57. 48.101 / 57. 48.101
libavformat    57. 41.100 / 57. 41.100
libavdevice    57.  0.101 / 57.  0.101
libavfilter     6. 47.100 /  6. 47.100
libavresample   3.  0.  0 /  3.  0.  0
libswscale      4.  1.100 /  4.  1.100
libswresample   2.  1.100 /  2.  1.100
libpostproc    54.  0.100 / 54.  0.100
```

**Comment by mikeboers** [comment]
Thanks for putting so much effort into this.

I've you've been looking at the PyAV source, do you happen to have a guess as to the culprit?

**Comment by scottywz** [comment]
I really don't.  I do see this in [the API docs for `av_buffersrc_write_frame()`](https://www.ffmpeg.org/doxygen/3.1/group__lavfi__buffersrc.html#ga786409c3f3910a0ab5fa6b23b4e7399b):  "frame frame to be added. If the frame is reference counted, this function will make a new reference to it. Otherwise the frame data will be copied."

**Comment by ArtanisCV** [comment]
Is there any progress on this issue? I also encounter the memory leak issue when using filters (pyav version: 6.2.0).
