### ISSUE TITLE
FFmpeg-like vsync logic

### ISSUE THREAD

**Issue by kharazi** [PyAV-Org/PyAV#225]
I want to sample specific video frames using this command:

`ffmpeg -i SampleVideo_1280x720_2mb.mp4 -vf select='eq(pict_type\,I)' -vsync 2 -s 1280x720 -f image2 thumbnails-%02d.jpeg
`
What's AV equievalent for this command and how can I pass select parameter in decode function?

```
container = av.open(path) 
for frame in container.decode(video=0, vsync=2, select='eq(pict_type\,I)') # ?
```

**Comment by mikeboers** [comment]
Unfortunately, the `vsync` parameter is not a simple one, and contains a ton of logic that we have not implemented. It would be great if we did, but that is out of scope for a long time.

I'm going to retitle this issue and leave it here.
