### ISSUE TITLE
codecs_available, fiters_available ordering

### ISSUE THREAD

**Issue by skirsdeda** [PyAV-Org/PyAV#247]
I would suggest making those *tuples* to keep the ordering intact. Is there any particular reason why *sets* are used? I don't think there are duplicate names in any of those lists.

**Comment by mikeboers** [comment]
I wonder if there is any reason to keeping the ordering intact.

I went with sets because I felt the main purpose of having them there was to test if a given codec was available. But... there any many uses so...

🤷‍♂️

**Comment by skirsdeda** [comment]
One could argue that the pythonic way is to ask forgiveness not permission :) So instead of checking whether something is available you just try to get it and if it fails, then do something about it.
And if we take filters for example, the order is pretty clear:
1) audio (filters / sources / sinks)
2) video (filters / sources / sinks)
3) multimedia (filters / sources)
And everything a-z inside groups. So there's some logic I guess...

**Comment by jlaine** [comment]
There is some overlap in the input / output formats (aka demuxers / muxers), for these the set makes sense;
