### ISSUE TITLE
Passing BytesIO object to av.open causes crash.

### ISSUE THREAD

**Issue by hhsprings** [PyAV-Org/PyAV#257]
This code causes crash:
```python
tmp = BytesIO()
# ... write bytes to tmp (for example wave format data) ...
container = av.open(tmp, "r")
```
We have to do `seek(0)` before calling open:
```python
tmp = BytesIO()
# ... write bytes to tmp (for example wave format data) ...
tmp.seek(0)
container = av.open(tmp, "r")
```
Of course the fact that the result is not what we want without `seek(0)` is no problem, but crashing application is no good.

**Comment by mikeboers** [comment]
Good to know. Any idea where it is?

(I haven't looked. 😉 )

**Comment by hhsprings** [comment]
> Any idea where it is?

Unfortunately, I don't know, too. Maybe it is not in PyAV itself but in libav.

Actually, the essential of this problem is just the fear for the end-user because of `application has stopped working` dialog (especially on Windows), not python's exception stacktrace. So, if PyAV can check `EOF` in advance and raise python's Exception, we might be happier.

I only imagine very straight-forward solution:
```python
if _file.read(1)  == "":  # check eof if file-object is seekable
    raise_exception = True
_file.seek(-1, 1)  # rewind (offset=-1, whence=SEEK_CUR)
if raise_exception:
    raise EOFError("...")
```

**Comment by hhsprings** [comment]
I could not detect the actual crashing point, but I think it is enough to modify [container/core.pyx#L65](https://github.com/mikeboers/PyAV/blob/master/av/container/core.pyx#L65)~ to:
```python
        # Setup Python IO.
        if self.file is not None:

            self.fread = getattr(self.file, 'read', None)
            self.fwrite = getattr(self.file, 'write', None)
            self.fseek = getattr(self.file, 'seek', None)
            self.ftell = getattr(self.file, 'tell', None)

            if not all((self.fread, self.fwrite, self.fseek, self.ftell)):
                raise TypeError(
                    "The file-object must have `read', `write', `seek', and `tell'.",
                    type(self.file))

            if not self.writeable:
                # Check EOF in advance.
                try:
                    if self.fread(1) == "":  # EOF
                        raise EOFError()
                finally:
                    self.fseek(-1, 1)
```

**Comment by jlaine** [comment]
Closing, we have extensive tests for Python I/O now
