### ISSUE TITLE
av.filter.Graph.add_abuffer()

### ISSUE THREAD

**Issue by hhsprings** [PyAV-Org/PyAV#260]
I noticed that using `av.filter.Graph` for audio is less blessed than for video. For video, `av.filter.Graph` exposes the convenient method `add_buffer`, but for audio `av.filter.Graph` has no `add_abuffer` ([abuffer](https://ffmpeg.org/ffmpeg-filters.html#Examples-13)). Do you have a plan for adding convenient method `add_abuffer` to `av.filter.Graph`? (Lacking of this is not fatal, but this situation is unbalanced.)

**Comment by hhsprings** [comment]
Sorry, in the first place, `av.filter.Graph' doesn't support audio?

**Comment by hhsprings** [comment]
If `add_abuffer` will be made, is this right? (At least for me it works very well.)
```python
    def add_abuffer(self, template=None, sample_rate=None, format=None, layout=None, channels=None, name=None):
        """
        Convenient method for adding `abuffer <https://ffmpeg.org/ffmpeg-filters.html#abuffer>`_.
        """

        if template is not None:
            if sample_rate is None:
                sample_rate = template.sample_rate
            if format is None:
                format = template.format
            if layout is None:
                layout = template.layout.name
            if channels is None:
                channels = template.channels

        if sample_rate is None:
            raise ValueError('missing sample_rate')
        if format is None:
            raise ValueError('missing format')
        if layout is None:
            raise ValueError('missing layout')
        if channels is None:
            raise ValueError('missing channels')

        args = "sample_rate=%d:sample_fmt=%s:channel_layout=%s:time_base=%d/%d" % (
            sample_rate, AudioFormat(format).name,
            layout,
            1, 1000,
        )

        return self.add('abuffer', args, name=name)
```
Because I'm not familiar with `timebase` and `AudioLayout`, so I am not confident.

Of course `push` should be modified:
```python
    def push(self, frame):

        if isinstance(frame, VideoFrame):
            contexts = self._context_by_type.get('buffer', [])
        elif isinstance(frame, AudioFrame):                      # ADD
            contexts = self._context_by_type.get('abuffer', [])  # ADD
        else:
            raise ValueError('can only push VideoFrame or AudioFormat', type(frame))
       # ...
```

**Comment by mikeboers** [comment]
We should have something for adding an audio buffer similar to the video one, but I guess the few of us working on filteres haven't really touched audio (as you can tell).

My guess is that the time base would be `1/sample_rate`, as I *think* that is what FFmpeg wants everywhere.

**Comment by notedit** [comment]
@hhsprings  do you still work on this.  i am tring to make audio filter work.

**Comment by notedit** [comment]
ok  figure out.

**Comment by notedit** [comment]
@hhsprings   i came to this error,   can you give some advice?

`
Format change is not supported
    fchain[0].push(ifr)
  File "av/filter/context.pyx", line 81, in av.filter.context.FilterContext.push
  File "av/utils.pyx", line 105, in av.utils.err_check
av.AVError: [Errno 1163346256] Not yet implemented in FFmpeg, patches welcome (libav.abuffersink: Format change is not supported)
`

`
import av
import av.filter


audio1 = 'audio1.mp3'
audio2 = 'audio2.mp3'

audio_out = 'audio_out.mp3'

container1 = av.open(audio1)
container2 = av.open(audio2)

at = next((s for s in container1.streams if s.type == 'audio'), None)


container_out = av.open(audio_out, "w")

out_stream = container_out.add_stream(template=at)

print(at.rate,at.layout.name,at.format.name)

args = "sample_rate=%d:sample_fmt=%s:channel_layout=%s:time_base=%d/%d" % (
    at.rate, at.format.name,
    at.layout.name,
    1, at.rate,
)

print(args)

graph = av.filter.Graph()

fchain = []
fchain.append(graph.add('abuffer',args))
fchain.append(graph.add('abuffersink'))
fchain[-2].link_to(fchain[-1])


for packet in container1.demux():
    
    for ifr in packet.decode():
        typ = packet.stream.type
        if typ == 'audio':
            #print(ifr)
            fchain[0].push(ifr)
            #print('push')
            ofr = fchain[-1].pull()
            # print(ofr)

`

**Comment by morrolinux** [comment]
I am too trying to make audio filter work. Is there any way at all as of yet?

**Comment by aspen1135** [comment]
Bump. It seems others are working on implementing add_abuffer in the [pull requests](https://github.com/mikeboers/PyAV/pull/389). For now, I'm using a subprocess to call FFmpeg when filters are needed since I can't seem to get the new `add_abuffer` to work either. add_abuffer would certainly be faster for my project and I will be using it whenever it's released (hopefully in the next release).

**Comment by egao1980** [comment]
Hi aspen1135, currently https://github.com/mikeboers/PyAV/pull/389 is functional - the builds for it fail due to CI issues. I'm going to compare our efforts and try to merge your changes into my PR if I've missed something. 
If something doesn't work for you - please drop me a comment and I'll fix it.

**Comment by aspen1135** [comment]
> Hi aspen1135, currently #389 is functional - the builds for it fail due to CI issues. I'm going to compare our efforts and try to merge your changes into my PR if I've missed something.
> If something doesn't work for you - please drop me a comment and I'll fix it.

Well I can't seem to test anything out, since all the source code changes are within pyx files which, correct me if I'm wrong, still needs to be built manually using Cython.

Having to build everything manually has been increasingly frustrating for me. I spent over a week or longer just trying to build the av module from source. I installed every single version of visual studio from 2015 to 2019, including setup tools and windows C++ build tools and no matter what I'd run into some sort of exception or error saying I'm missing something. I eventually just caved and just installed the module via anaconda.

See [this](https://github.com/mikeboers/PyAV/issues/531). It's still unresolved, as I don't think anyone knows why it is happening and assume it is user error despite my persistent efforts. It would be great to see some of these filter/graph changes pushed to the anocanda repository. Otherwise, I'm not confident I'll be able to use them anytime soon. I don't want to waste many additional days dealing with environment build tool errors despite following over 4 or 5 tutorials to a T.

**Comment by egao1980** [comment]
On building locally - try the `python setup.py build_ext --inplace`.  `pip install github-url` also works. #389 is working both on Windows 10 and Mac OS X for me. I'm using vanilla Python on Mac. I'll review the build issue you've sent as I do not remember the details for the Windows build. Keep in touch.

**Comment by aspen1135** [comment]
> On building locally - try the `python setup.py build_ext --inplace`. `pip install github-url` also works. #389 is working both on Windows 10 and Mac OS X for me. I'm using vanilla Python on Mac. I'll review the build issue you've sent as I do not remember the details for the Windows build. Keep in touch.

I tried installing from github just now. No dice. As expected, it says I am missing an include file "io.h". This is after I've installed the latest visual studio (2019), as well as C++ and all build-tools related resources in the visual studio installer. Local is the same result.

![image](https://user-images.githubusercontent.com/17952043/61783913-9020be80-adbd-11e9-8d0f-b72057c4a22b.png)


```
(base) C:\Users\Aspen>pip install git+https://github.com/mikeboers/PyAV
Collecting git+https://github.com/mikeboers/PyAV
  Cloning https://github.com/mikeboers/PyAV to c:\users\aspen\appdata\local\temp
\pip-req-build-n4q0xvf1
  Running command git clone -q https://github.com/mikeboers/PyAV 'C:\Users\Aspen
\AppData\Local\Temp\pip-req-build-n4q0xvf1'
Building wheels for collected packages: av
  Building wheel for av (setup.py) ... error
  ERROR: Complete output from command 'C:\ProgramData\Anaconda3\python.exe' -u -
c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\Aspen\\AppData\\Local\\T
emp\\pip-req-build-n4q0xvf1\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', o
pen)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exe
c(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Aspen\AppDa
ta\Local\Temp\pip-wheel-ukt23nwf' --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\av
  copying av\datasets.py -> build\lib.win-amd64-3.7\av
  copying av\deprecation.py -> build\lib.win-amd64-3.7\av
  copying av\__init__.py -> build\lib.win-amd64-3.7\av
  copying av\__main__.py -> build\lib.win-amd64-3.7\av
  creating build\lib.win-amd64-3.7\av\audio
  copying av\audio\__init__.py -> build\lib.win-amd64-3.7\av\audio
  creating build\lib.win-amd64-3.7\av\codec
  copying av\codec\__init__.py -> build\lib.win-amd64-3.7\av\codec
  creating build\lib.win-amd64-3.7\av\container
  copying av\container\__init__.py -> build\lib.win-amd64-3.7\av\container
  creating build\lib.win-amd64-3.7\av\data
  copying av\data\__init__.py -> build\lib.win-amd64-3.7\av\data
  creating build\lib.win-amd64-3.7\av\filter
  copying av\filter\__init__.py -> build\lib.win-amd64-3.7\av\filter
  creating build\lib.win-amd64-3.7\av\subtitles
  copying av\subtitles\__init__.py -> build\lib.win-amd64-3.7\av\subtitles
  creating build\lib.win-amd64-3.7\av\video
  copying av\video\__init__.py -> build\lib.win-amd64-3.7\av\video
  running build_ext
  running config
  writing build\temp.win-amd64-3.7\Release\include\pyav\config.h
  running cythonize
  Compiling av\buffer.pyx because it changed.
  [1/1] Cythonizing av\buffer.pyx
  Compiling av\bytesource.pyx because it changed.
  [1/1] Cythonizing av\bytesource.pyx
  Compiling av\descriptor.pyx because it changed.
  [1/1] Cythonizing av\descriptor.pyx
  Compiling av\dictionary.pyx because it changed.
  [1/1] Cythonizing av\dictionary.pyx
  Compiling av\enums.pyx because it changed.
  [1/1] Cythonizing av\enums.pyx
  Compiling av\format.pyx because it changed.
  [1/1] Cythonizing av\format.pyx
  Compiling av\frame.pyx because it changed.
  [1/1] Cythonizing av\frame.pyx
  Compiling av\logging.pyx because it changed.
  [1/1] Cythonizing av\logging.pyx
  Compiling av\option.pyx because it changed.
  [1/1] Cythonizing av\option.pyx
  Compiling av\packet.pyx because it changed.
  [1/1] Cythonizing av\packet.pyx
  Compiling av\plane.pyx because it changed.
  [1/1] Cythonizing av\plane.pyx
  Compiling av\stream.pyx because it changed.
  [1/1] Cythonizing av\stream.pyx
  Compiling av\utils.pyx because it changed.
  [1/1] Cythonizing av\utils.pyx
  Compiling av\_core.pyx because it changed.
  [1/1] Cythonizing av\_core.pyx
  Compiling av\audio\codeccontext.pyx because it changed.
  [1/1] Cythonizing av\audio\codeccontext.pyx
  Compiling av\audio\fifo.pyx because it changed.
  [1/1] Cythonizing av\audio\fifo.pyx
  Compiling av\audio\format.pyx because it changed.
  [1/1] Cythonizing av\audio\format.pyx
  Compiling av\audio\frame.pyx because it changed.
  [1/1] Cythonizing av\audio\frame.pyx
  Compiling av\audio\layout.pyx because it changed.
  [1/1] Cythonizing av\audio\layout.pyx
  Compiling av\audio\plane.pyx because it changed.
  [1/1] Cythonizing av\audio\plane.pyx
  Compiling av\audio\resampler.pyx because it changed.
  [1/1] Cythonizing av\audio\resampler.pyx
  Compiling av\audio\stream.pyx because it changed.
  [1/1] Cythonizing av\audio\stream.pyx
  Compiling av\codec\codec.pyx because it changed.
  [1/1] Cythonizing av\codec\codec.pyx
  Compiling av\codec\context.pyx because it changed.
  [1/1] Cythonizing av\codec\context.pyx
  Compiling av\container\core.pyx because it changed.
  [1/1] Cythonizing av\container\core.pyx
  Compiling av\container\input.pyx because it changed.
  [1/1] Cythonizing av\container\input.pyx
  Compiling av\container\output.pyx because it changed.
  [1/1] Cythonizing av\container\output.pyx
  Compiling av\container\pyio.pyx because it changed.
  [1/1] Cythonizing av\container\pyio.pyx
  Compiling av\container\streams.pyx because it changed.
  [1/1] Cythonizing av\container\streams.pyx
  Compiling av\data\stream.pyx because it changed.
  [1/1] Cythonizing av\data\stream.pyx
  Compiling av\filter\context.pyx because it changed.
  [1/1] Cythonizing av\filter\context.pyx
  Compiling av\filter\filter.pyx because it changed.
  [1/1] Cythonizing av\filter\filter.pyx
  Compiling av\filter\graph.pyx because it changed.
  [1/1] Cythonizing av\filter\graph.pyx
  Compiling av\filter\link.pyx because it changed.
  [1/1] Cythonizing av\filter\link.pyx
  Compiling av\filter\pad.pyx because it changed.
  [1/1] Cythonizing av\filter\pad.pyx
  Compiling av\subtitles\codeccontext.pyx because it changed.
  [1/1] Cythonizing av\subtitles\codeccontext.pyx
  Compiling av\subtitles\stream.pyx because it changed.
  [1/1] Cythonizing av\subtitles\stream.pyx
  Compiling av\subtitles\subtitle.pyx because it changed.
  [1/1] Cythonizing av\subtitles\subtitle.pyx
  Compiling av\video\codeccontext.pyx because it changed.
  [1/1] Cythonizing av\video\codeccontext.pyx
  Compiling av\video\format.pyx because it changed.
  [1/1] Cythonizing av\video\format.pyx
  Compiling av\video\frame.pyx because it changed.
  [1/1] Cythonizing av\video\frame.pyx
  Compiling av\video\plane.pyx because it changed.
  [1/1] Cythonizing av\video\plane.pyx
  Compiling av\video\reformatter.pyx because it changed.
  [1/1] Cythonizing av\video\reformatter.pyx
  Compiling av\video\stream.pyx because it changed.
  [1/1] Cythonizing av\video\stream.pyx
  building 'av.buffer' extension
  creating build\temp.win-amd64-3.7\Release\src
  creating build\temp.win-amd64-3.7\Release\src\av
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14
.21.27702\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Dinline=__
inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -
Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=
__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline
 -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinlin
e=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inli
ne -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinl
ine=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__in
line -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Di
nline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__
inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Iinclude -IC:\Prog
ramData\Anaconda3\include -Ibuild\temp.win-amd64-3.7\Release\include -IC:\Progra
mData\Anaconda3\include -IC:\ProgramData\Anaconda3\include -Ibuild\temp.win-amd6
4-3.7\Release\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Com
munity\VC\Tools\MSVC\14.21.27702\ATLMFC\include" "-IC:\Program Files (x86)\Micro
soft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include" /Tcsrc\av\b
uffer.c /Fobuild\temp.win-amd64-3.7\Release\src\av\buffer.obj
  buffer.c
  C:\ProgramData\Anaconda3\include\pyconfig.h(59): fatal error C1083: Cannot ope
n include file: 'io.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Commun
ity\\VC\\Tools\\MSVC\\14.21.27702\\bin\\HostX86\\x64\\cl.exe' failed with exit s
tatus 2
```

**Comment by egao1980** [comment]
This just means that you're missing INCLUDE env variable that points to `io.h` see https://stackoverflow.com/questions/40018405/cython-cannot-open-include-file-io-h-no-such-file-or-directory

The easiest solution is to install Windows 10 development kit. And it should work.

Hard way, you can try the following:
- run the C:\Program Files (x86)\Microsoft Visual Studio\Shared\14.0\VC\vcvarsall.bat or similar batch in the shell before doing build
- manually / semi-automatically add relevant variables (replace Windows SDK kit path with the actual locations):
```
where cl >nul 2>nul || "%VS140COMNTOOLS%..\..\VC\vcvarsall.bat" amd64
set INCLUDE=C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt
set LIB=C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\um\x64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\ucrt\x64
python setup.py build_ext --inplace
```

**Comment by aspen1135** [comment]
> This just means that you're missing INCLUDE env variable that points to `io.h` see https://stackoverflow.com/questions/40018405/cython-cannot-open-include-file-io-h-no-such-file-or-directory
> 
> The easiest solution is to install Windows 10 development kit. And it should work.

I will try this now. Not sure if it will work as I am on windows 7 ultimate x64. I will update this in a few moments. If it does not work, I will continue troubleshooting this in the morning since it's close to 4am.

Thanks for your help in this matter.

**Comment by egao1980** [comment]
This might require more work, as AppVeyor x64 build in conda 3.7 also fails. Try either 3.6 or 32 bit Python / FFMpeg.

**Comment by aspen1135** [comment]
> This might require more work, as AppVeyor x64 build in conda 3.7 also fails. Try either 3.6 or 32 bit Python / FFMpeg.

Tried working on this more today. Ran into some more problems.

I downloaded and installed python 3.6 to a seperate location. I made sure to clear my PATH variables and ensure the running python was on 3.6.

The first thing I ran into, was it was still not detecting the C++ compiler in the path and throwing a cl.exe error 'no file found'. So I added `'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\` to PATH and fixed that error.

Next I ran into `io.h not found`, and added `C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt;` to PATH. Interestingly enough, this error would still be thrown regardless of it being added to PATH. I can even open the `io.h` script directly by typing "io.h" into the cmd shell.

So next thing I tried was just to copy/paste all the `.h` scripts into the `Python 3.6\include` folder. This got me past the `io.h` error.

Now it's wanting another missing script from `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.16.27023\include` so I add that to PATH and the same error occurs, so I instead copy those resources into `Python 3.6\include` and get passed that.

And then another missing script error occurs.

There HAS to be an easier way to do this. Why can't python find any of my visual studio resources after being added to PATH?

**Comment by egao1980** [comment]
It's not PATH but INCLUDE and LIB for `io.h`. Please check what `vcvarsall.bat` file does. Hope that helps.

**Comment by aspen1135** [comment]
> It's not PATH but INCLUDE and LIB for `io.h`. Please check what `vcvarsall.bat` file does. Hope that helps.

I do not see an INCLUDE or LIB in my list of Windows environment variables. Do I have to manually create these?

PS. I have already tried running vcvarsall.bat and have included it in my PATH directory.

**Comment by jlaine** [comment]
`Graph.add_abuffer` has been around for a while and is actively used by the current `AudioResampler` implementation
