### ISSUE TITLE
Frame timestamps when transcoding must be set to None

### ISSUE THREAD

**Issue by MiguelFRomeroR** [PyAV-Org/PyAV#281]
I was able to replicate this issue with the following example:
```python
from fractions import Fraction
import av
import logging
logging.basicConfig()

input_container = av.open('input.mp4')
video_stream = input_container.streams.video[0]

output_container = av.open('output.mp4', mode='w')
stream = output_container.add_stream('libx264', rate=Fraction(30000,1001))
stream.width = 512
stream.height = 512
stream.pix_fmt = 'yuv420p'

for frame in input_container.decode(video=0):
	packet = stream.encode(frame)
	output_container.mux(packet)

packet = stream.encode()
output_container.mux(packet)

output_container.close()
```
The fps of the file 'output.mp4' is 0.06 fps, and therefore the duration of the video is really high. I tried lots of things (changing the rate, time_base, bit_rate, max_bit_rate, ...  of the OutputContainer and the CodecContext), until I found out that to solve it, you simply have to set frame.pts and frame.time_base to None, to allow the encoder to generate it's own timestamps.

```python
from fractions import Fraction
import av
import logging
logging.basicConfig()

input_container = av.open('input.mp4')
video_stream = input_container.streams.video[0]

output_container = av.open('output.mp4', mode='w')
stream = output_container.add_stream('libx264', rate=Fraction(30000,1001))
stream.width = 512
stream.height = 512
stream.pix_fmt = 'yuv420p'

for frame in input_container.decode(video=0):
	frame.pts = None
	frame.time_base = None
	packet = stream.encode(frame)
	output_container.mux(packet)

packet = stream.encode()
output_container.mux(packet)

output_container.close()
```
This error is very subtle but I wanted to remark it, because someone else may have a related issue.

I'm using the latest _(31-01-2018)_ ffmpeg version N-89907-g293f24b, the PyAV version built from source under Ubuntu 16.04.

**Comment by mikeboers** [comment]
This should land in the documentation, as PyAV/FFmpeg are working as they need to.

**Comment by jlaine** [comment]
Could this be due to the fact the frames had a bogus timebase until recently?

**Comment by jlaine** [comment]
I ran the following, which worked fine using PyAV 0.5.1:

```
import av
import logging
logging.basicConfig()

input_container = av.open('input.mp4')
video_stream = input_container.streams.video[0]

output_container = av.open('output.mp4', mode='w')
stream = output_container.add_stream('libx264')
stream.width = 512
stream.height = 512
stream.pix_fmt = 'yuv420p'
stream.time_base = video_stream.time_base

for frame in input_container.decode(video=0):
    packet = stream.encode(frame)
    output_container.mux(packet)

output_container.close()
```

**Comment by mikeboers** [comment]
@jlaine It might have been the wrong timebase on the frames.

My comment from Mar. 21 was because I thought the timebase didn't match on the two streams (which it wouldn't), and so if you don't remap the pts from one to the other it will be wonky. But that is what the great time overhaul of v0.4.0 was supposed to do at all.

This could very likely be fixed, but I'm leaving the issue here as a signal to document that time needs your attention all the time.

**Comment by zhiweny1122** [comment]
the Pyav always create B frames when I use it in aiortc .
Can you tell me how to diable B frame in libx264 codec of pyav ?
It doesn't work even though I set the pts and time_base to None.
** pts 297 vlastpts 1403085 dts 296 kind video
*** pts 302 vlastpts 1406848 dts 297 kind video
*** pts 300 vlastpts 1424436 dts 298 kind video
*** pts 299 vlastpts 1430097 dts 299 kind video
*** pts 301 vlastpts 1431405 dts 300 kind video
*** pts 306 vlastpts 1432548 dts 301 kind video
*** pts 304 vlastpts 1434336 dts 302 kind video
*** pts 303 vlastpts 1437813 dts 303 kind video
*** pts 305 vlastpts 1441016 dts 304 kind video
*** pts 308 vlastpts 1444272 dts 305 kind video
*** pts 307 vlastpts 1449291 dts 306 kind video
*** pts 310 vlastpts 1452114 dts 307 kind video
*** pts 309 vlastpts 1456847 dts 308 kind video
*** pts 311 vlastpts 1460187 dts 309 kind video
*** pts 315 vlastpts 1464119 dts 310 kind video
*** pts 313 vlastpts 1469300 dts 311 kind video

**Comment by zzjjbb** [comment]
> 
> 
> I ran the following, which worked fine using PyAV 0.5.1:
> 
> ```python
> import av
> import logging
> logging.basicConfig()
> 
> input_container = av.open('input.mp4')
> video_stream = input_container.streams.video[0]
> 
> output_container = av.open('output.mp4', mode='w')
> stream = output_container.add_stream('libx264')
> stream.width = 512
> stream.height = 512
> stream.pix_fmt = 'yuv420p'
> stream.time_base = video_stream.time_base
> 
> for frame in input_container.decode(video=0):
>     packet = stream.encode(frame)
>     output_container.mux(packet)
> 
> output_container.close()
> ```
> 
> As you can see:
> 
>     * I didn't pass the `rate` parameter when opening the container, but copied `time_base` from the input to the output stream
> 
>     * I didn't touch the frames' `pts` or `time_base`
> 
>     * I didn't use the final `stream.encode()`, as this results in a packet with no PTS causing ffmpeg to bomb
> 
> 
> The output file has the exact same framerate as my input.

I guess you need to encode a `None` and mux the output after finish decoding and before close the container, in order to flush the encoder?

**Comment by jlaine** [comment]
To the best of my knowledge this is fixed
