### ISSUE TITLE
Input vfr video stream.rate can be used to set output stream only after decode

### ISSUE THREAD

**Issue by czfhhh** [PyAV-Org/PyAV#285]
Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)] on win32
     "help", "copyright", "credits" or "license" for more information.
    >>> import av
    >>> av._core.pyav_version
    '0.4.0.dev0'
    >>> input = av.open("E:/temp/input.mp4")
    >>> invstream = input.streams.video[0]
    >>> invstream.rate
    Fraction(1662300005, 55649452) 
    >>> frame = next(input.decode(video=0))
    >>> invstream.rate
    Fraction(60, 1)
At first stream.rate == stream.average_rate, after decode one frame, it changed. When processing vfr video, if set it to output stream rate before decode, it cause an error below:

    non-strictly-monotonic PTS
    Application provided invalid, non monotonically increasing dts to muxer in stream 0: 1780782464 >= 1780782464
The code I used finally as below, for others reference.

    import av
    from tqdm import tqdm
    
    input = av.open("E:/temp/input.mp4")
    invstream = input.streams.video[0]
    inastream = input.streams.audio[0]
    
    frame = next(input.decode(video=0))
    
    output = av.open("E:/temp/output.mp4", 'w')
    outvstream = output.add_stream('libx264', invstream.rate)
    outvstream.pix_fmt = invstream.pix_fmt
    outvstream.height = invstream.height
    outvstream.width = invstream.width
    outvstream.options = {"preset":"medium","tune":"film","crf":"22"}
    outastream = output.add_stream(template=inastream)
    outastream.options = {}
    
    seekstart = 0
    durationtime = 1000000
	endtime = seekstart + durationtime
    input.seek(seekstart*1000000)
    
    videopackets = []
    audiopackets = []
    for inpacket in input.demux():
        if inpacket.stream.type == "video":
            videopackets.append(inpacket)
            if len(audiopackets) > 0:
                break
        elif inpacket.stream.type == "audio":
            audiopackets.append(inpacket)
            if len(videopackets) > 0:
                break
    videostart = videopackets[0].pts * invstream.time_base
    audiostart = audiopackets[0].pts * inastream.time_base            
    if videostart <= audiostart:
        vbasepts = videopackets[0].pts
        abasepts = round(videostart / inastream.time_base)
    else:
        abasepts = audiopackets[0].pts
        vbasepts = round(audiostart / invstream.time_base)
    
    d = min(endtime, invstream.duration * invstream.time_base) - videostart
    pbar = tqdm(total=(int(d*invstream.average_rate)+1))
    def video_mux_one(inpacket):
        for frame in inpacket.decode():
		
		    # You can process frame here
			
            new_frame.pts = frame.pts - vbasepts
            new_frame.time_base = invstream.time_base
            for outpacket in outvstream.encode(new_frame):
                output.mux(outpacket)
            pbar.update(1)
    
    def audio_mux_one(inpacket):
        inpacket.stream = outastream
        inpacket.pts -= abasepts
        inpacket.dts -= abasepts
        output.mux(inpacket)
    
    for inpacket in videopackets:
        video_mux_one(inpacket)
    for inpacket in audiopackets:
        audio_mux_one(inpacket)
    
    for inpacket in input.demux():
        if inpacket.stream.type == "video":
            video_mux_one(inpacket)
        elif (inpacket.stream.type == "audio") and inpacket.pts:
            if (inpacket.pts * inastream.time_base) > endtime:
                break
            audio_mux_one(inpacket)
    pbar.close()
            
    for outpacket in outvstream.encode(None):
        output.mux(outpacket)
    
    output.close()

**Comment by jlaine** [comment]
When you query `stream.rate` you are not actually querying the stream's framerate but the CodecContext's, which is probably only initialised after it has decoded something. Try using `Stream.average_rate` ?
