### ISSUE TITLE
Cannot open byte stream?

### ISSUE THREAD

**Issue by Data-drone** [PyAV-Org/PyAV#308]
I have some video coming in as a byte stream which I have saved into a variable.

I ran:

     av.open(test_stream_snipper)

and I get:

    TypeError: 'NoneType' object is not callable

am I missing some arguments?

**Comment by mikeboers** [comment]
What does the rest of the traceback look like, and what is `test_stream_snipper`?

**Comment by Data-drone** [comment]
the `test_stream_snippet` is a 4096 length byte code snippet of video.
eg (I've just typed that but it looks something like this)

`b'\x4565\234s\234fsdf23\234sdf'`

I will get back to you on the traceback.

**Comment by Data-drone** [comment]
@Kamekameha is there a way to consuming a datastream with PyAV?

**Comment by mikeboers** [comment]
The container API is like a generator that you pull on, while the codec API is like a coroutine that you push on.

If your bytes represent a container, you can either wrap the complete bytestream in a `StringIO` or `BytesIO`, or write something which provides at least `read` (maybe `tell`) and blocks when it needs new data.

If your bytes represent a single codec, then you can make a `CodecContext`, and keep on making `Packet`s from your data and decoding them. If they aren't already structured, there is a parsing API, but I don't recall how finished it is.

Things that would be neat for us to investigate:
- Assert that we only need a `read` method.
- Assert that containers could work in a non-blocking way (erroring in a way that indicates that they are finished).
- Assert the parsing API works.

Keep us in the loop!

**Comment by mikeboers** [comment]
We do set [`AVIO_SEEKABLE_NORMAL`](https://www.ffmpeg.org/doxygen/3.3/avio_8h.html#a03ea0dfa113a05f4843bbfff69e0cd0a) (but should stop if there is no `seek` method), and we could set [`AVIO_FLAG_NONBLOCK`](https://www.ffmpeg.org/doxygen/3.3/avio_8h.html#aea3131c92c70177e463538e9a6b4308e) optionally (but it is noted that this is a work in progress).

**Comment by Data-drone** [comment]
depending on the number of byes I feed in after wrapping it in `io,BytesIO` the result can be quite different.

I get this a lot:
```
Format mp3 detected only with low score of 1, misdetection possible!
Failed to read frame size: Could not seek to 12277.
```

sometimes It detects one dimension but wrongly.

Is there a way to specify frame size in `av.open`?

My format is this spec from the example:

```
stream.width = 1824
stream.height = 1376
stream.pix_fmt = 'yuv420p'
```

**Comment by HassanNaseri** [comment]
I have a byte stream (AWS Kinesis Stream) with an object that provides `read()` method, but I get an error when trying to open it:

```
Traceback (most recent call last):
  File "<ipython-input-13-bff66e67a140>", line 1, in <module>
    open(stream_payload)
  File "av/container/core.pyx", line 255, in av.container.core.open
  File "av/container/core.pyx", line 211, in av.container.core.Container.__cinit__
  File "av/container/core.pyx", line 112, in av.container.core.ContainerProxy.__init__
  File "av/container/core.pyx", line 183, in av.container.core.ContainerProxy.err_check
  File "av/utils.pyx", line 105, in av.utils.err_check
AVError: [Errno 1094995529] Invalid data found when processing input: 'None' (16: matroska,webm)
```

Wrapping a video chunk in `io.BytesIO` did not help as well, as I get the following error trying to open the wrapped stream:

```
Read error
Out[14]: <av.InputContainer <_io.BytesIO object at 0x11cf69fc0>>
```

**Comment by jlaine** [comment]
`BytesIO` is fully supported both for input and output, closing.
