### ISSUE TITLE
Improve file-like IO.

### ISSUE THREAD

**Issue by mikeboers** [PyAV-Org/PyAV#309]
Spurred from #308:

- [x] Assert `read` and `write` exist when nessesary.
- [ ] Expose [`AVIO_FLAG_NONBLOCK`](https://www.ffmpeg.org/doxygen/3.3/avio_8h.html#aea3131c92c70177e463538e9a6b4308e).
- [x] Don't set [`AVIO_SEEKABLE_NORMAL`](https://www.ffmpeg.org/doxygen/3.3/avio_8h.html#a03ea0dfa113a05f4843bbfff69e0cd0a) if there is no `seek` (or a kwarg or something).
- [ ] Assert the parsing API works.

**Comment by jlaine** [comment]
As far as I can tell, we now correctly detect read / write / seek.

I'm not sure AVIO_FLAG_NONBLOCK is a good idea, it carries a warning that it's work in progress even in FFmpeg 4.0:

https://www.ffmpeg.org/doxygen/4.0/avio_8h.html#aea3131c92c70177e463538e9a6b4308e

What do you mean by "assert the parsing API works" ?

**Comment by mikeboers** [comment]
I mean [this](https://github.com/mikeboers/PyAV/blob/develop/av/codec/context.pyx#L173-L230).

It is for splitting a bytestream into packets that the codec will like.

**Comment by jlaine** [comment]
Haha:

`def parse(self, str input_, allow_stream=False)`

str? that's off to a good start :)

**Comment by mikeboers** [comment]
I think I wrote this in one go and never looked at it again. It is not anything I consider done or supported.

So... yeah. It's going to be a source of awesome.

**Comment by mephi42** [comment]
It would also be great if PyAV considered an object non-seekable if it has a [`seekable()`](https://docs.python.org/3/library/io.html#io.IOBase.seekable) method, which returns `False`. Otherwise it's not possible to use non-seekable objects derived from `io.IOBase`.

**Comment by jlaine** [comment]
The file-like I/O support is in a good place, especially since 4fa70f8073708a56fa816c08ef6fae74611d3df0 so I'm closing this.
