### ISSUE TITLE
Example: RTSP to segmented MP4.

### ISSUE THREAD

**Issue by mikeboers** [PyAV-Org/PyAV#358]
Carrying from #302. CC @alexhutnik.

Lets make a nice short example for remuxing from RTSP to MP4 containers, cutting periodically to result in fully playable files.

Key things:

- Must rewrite pts/dts of each packet so that first one in the file starts at zero.
- Must cut at keyframes (under the assumption that your source includes the picture/stream setting NALs with every keyframe... which my cameras do).
- Work around dumb `options` bug that I still haven't dealt with.

**Comment by viskoo** [comment]
Here is an example of how i manage splitting files and dts/pts rescaling (still use it only for testing )
```
import av
import time

in_container = av.open("rtsp://path/to/stream", "r")
video_stream = in_container.streams.video[0]

out_container = None

def start_container(stream, timestamp):
    global out_container
    filename = "./file_" + str(timestamp) + ".mp4"
    out_container = av.open(filename, "w", format="mp4")
    outstream = out_container.add_stream(template=stream)
    outstream.options = {}

def stop_container():
    global out_container
    out_container.close()
    out_container = None

first_packet = True
rescaling_nr = 0
clip_duration = 60 * 1000 #60 seconds
first_frame_timestamp = int(time.time() * 1000)

for packet in in_container.demux(video_stream):
    if first_packet:
        packet.dts = 0
        packet.pts = 0
        first_packet = False

    cur_timestamp = int(time.time() * 1000)
    if packet.is_keyframe and (cur_timestamp - first_frame_timestamp) >= clip_duration:
        stop_container()

    if out_container is None:
        start_container(video_stream, cur_timestamp)
        rescaling_nr = packet.dts
        first_frame_timestamp = cur_timestamp

    packet.pts -= rescaling_nr
    packet.dts -= rescaling_nr

    out_container.mux_one(packet)

````

**Comment by victorhcm** [comment]
> Must cut at keyframes (under the assumption that your source includes the picture/stream setting NALs with every keyframe... which my cameras do).

How can I check that?
