### ISSUE TITLE
Decoding with thread_type |= FRAME blocks at exit.

### ISSUE THREAD

**Issue by mikeboers** [PyAV-Org/PyAV#367]
Try `python examples/decode.py -c1 -t AUTO` on something that can have per-frame threads, and watch it block at the end.

**Comment by mikeboers** [comment]
I've tried going through all the deconstructors, and closes, etc., and can't find anything.

**Comment by jlaine** [comment]
What qualifies as "something that can have per-frame threads"? I've tried throwing a couple of videos at it and I don't get a hang (ffmpeg 4, on Debian/buster)

**Comment by jlaine** [comment]
Hi again @mikeboers what file (preferably FATE suite) can I use to reproduce this?

**Comment by jlaine** [comment]
Same as #909, it's related to the logging framework.
