### ISSUE TITLE
What is most reasonable method to crop frames?

### ISSUE THREAD

**Issue by mikeboers** [PyAV-Org/PyAV#392]
This is mostly for the examples/docs. Is there a filter for cropping, or do we drop to another layer (e.g. `PIL` or `numpy`)?

**Comment by jlaine** [comment]
I'm starting to gain a better understanding of how data is layed out in the frames, I'll try to circle back to this.

**Comment by jlaine** [comment]
Just FYI my motivation here was not actually cropping the frames, but extracting only the meaningful pixels (i.e. get rid of the padding that an AVFrame may contain). I think we should expose the "linesize" in our plane objects, it's needed for two purposes:

- detecting frames which have padding (when your width is not 16-byte aligned usually). Currently you can sort of get this information by dividing buffer_size by the height

- handling "negative strides", i.e when you have vertically flipped images. There is currently no way to get to this information: our abstraction loses this information as buffer_size is calculated as abs(linesize) * height

**Comment by jlaine** [comment]
It turns out we already have `Plane.line_size`, my mistake. So for example on a YUV420p frame you can do:

```
for i, plane in enumerate(frame.planes):
    # the full plane, with padding
    arr = numpy.frombuffer(plane, numpy.uint8).reshape(-1, plane.line_size)

    # the meaningful part of the frame
    div = 2 if i else 1
    arr = arr[:(frame.height // div), :(frame.width // div)]
```

As far as I'm concerned we can close this.
