### ISSUE TITLE
Stop protecting the users so much.

### ISSUE THREAD

**Issue by mikeboers** [PyAV-Org/PyAV#429]
We don't need to stop the users from shooting themselves in the foot as much as we do. It leads to some convoluted and difficult to maintain code (keeping so much in `__cinit__` instead of `__init__`, and encapsulating so much of the enums in a way that PyPy is unhappy with).

As long as they use the public API, and don't forget to call `super` when extending, let it segfault on them.

Agreed?

(The only results of this are my peace of mind, and I'll add a bit to the `HACKING.rst` file to remind me).

**Comment by jlaine** [comment]
This wasn't exactly the point I was making was specifically for the container / stream stuff. I was pointing out that:

- some operations may not be safe to do in `__cinit__`

- it's very hard to navigate the calls which are spread across `Container`, `ContainerProxy`, `InputContainer` and `OutputContainer`

I don't think subclassing is a real usecase, so much of the API is encapsulated in inaccessible Cython code (good!).

**Comment by mikeboers** [comment]
It is more the enums for me. It is okay that the user can blow it up if they do something really bad.

**Comment by jlaine** [comment]
@mikeboers this issue seems a bit "meta" I don't think it's going anywhere.. close it?
