### ISSUE TITLE
Remove "strict" option from open / close operations?

### ISSUE THREAD

**Issue by jlaine** [PyAV-Org/PyAV#438]
I am not sure how useful these options are, and think we should just adopt the tolerant behaviour (which is the default) in all cases.

This would be consistent with Python's file-like objects which are quite happy with being closed multiple times.

```
fp = open('bob.txt', 'w')
fp.close()
fp.close()
```

**Comment by jlaine** [comment]
@mikeboers any thoughts on this?

**Comment by mikeboers** [comment]
My initial thought is I would prefer to go the other direction, but as long as there is a `closed` attribute (which is also what Python does with `file`) and any actual operations with the thing besides hitting `close()` raise exceptions, then I'm very happy to drop the `strict` in these cases.

**Comment by mikeboers** [comment]
To be clear: remove `strict`, but have public read-only `closed` attribute.
