### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by mikeboers** [PyAV-Org/PyAV#439]
Short notes from a conversation I’m having:

- current contents of examples directory moved (to scratch or something)
- new examples in nicely organized hierarchy in examples directory
- they are runnable from terminal
- they have all imports and whatever they need
- special comment syntax let’s you omit parts from rendered html (like doctest directives)
- rendered examples are copy paste able in their full form
- every example turns into a test in the main test suite. Comment syntax let’s you add assertions that don’t get rendered
- interactive interpreter examples are handles fully via sphinx’s mechanics

**Comment by kli-nlpr** [comment]
waiting for more examples!
thx
