### ISSUE TITLE
Contributor guidelines

### ISSUE THREAD

**Issue by mikeboers** [PyAV-Org/PyAV#440]
From @jlaine [here](https://github.com/mikeboers/PyAV/pull/436#issuecomment-429611340):

- Move the changelog guidelines out of there and into `CONTRIBUTING.rst` (or whatever).
- Discuss testing, documentation, code formatting and style, etc..

[This](https://cryptography.io/en/latest/development/submitting-patches/) is a lovely example.

**Comment by jlaine** [comment]
I'm going to close this, style is handled automatically :)
