### ISSUE TITLE
Add a pythonic way to create a filter graph

### ISSUE THREAD

**Issue by orf** [PyAV-Org/PyAV#441]
If you want to automatically rotate an `av.Video` you need to create a `av.filter.Graph()` and create some form of chain. [This comment shows one such way](https://github.com/mikeboers/PyAV/issues/239#issuecomment-316536363)

It would be really nice if there was a more pythonic way of creating this chain. Something like this for example?

```python
graph = av.filter.Graph()
chain = graph.chain() | 'vflip' | 'hflip' | 'dilation' | 'buffersink'
```

Or

```
chain = graph.chain(
    'vflip', 'hflip', 'dilation', 'buffersink'
)
```

For the simple case this would call `link_to` in the correct order, and the `chain` object could be a callable that would push a frame into the first part of the chain and return the result from the last section?

Right now it's pretty ugly to do this, but it's a somewhat common use case I think?

**Comment by jb-alvarado** [comment]
I just wanted to point out that filters can have multiple inputs and outputs. This possibility should be given in any case. Also an filter output can be used much later in the chain, this should be considered.

**Comment by jlaine** [comment]
It has been over 3 years and no-one has picked this up, closing.
