### ISSUE TITLE
Python access to AVFrame metadata

### ISSUE THREAD

**Issue by shenberg** [PyAV-Org/PyAV#477]
Lack of this makes some filters useless - e.g. `silencedetect` which adds a 'silence_start' and/or 'silence_end' key to the frame's metadata when detected - see [source](https://github.com/FFmpeg/FFmpeg/blob/c782e7aa9e981a2f27db3f3afced5a6f10d6f8d9/libavfilter/af_silencedetect.c#L88)

**Comment by shersonb** [comment]
I would also be interested in this, as I would like access to lavfi.scene_score and data from the blackdetect filter. I currently have to run a ffprobe subprocess to do this.
