### ISSUE TITLE
VideoFrame.from_ndarray(img) fails for widths that are not a multiple of 8

### ISSUE THREAD

**Issue by gatagat** [PyAV-Org/PyAV#478]
Any call to `VideoFrame.from_ndarray(img)` fails if the image width is not a multiple of 8.

Error message:
```
ValueError                                Traceback (most recent call last)
      5 av.VideoFrame.from_ndarray(img) # <- OK
      6 img = np.zeros((100, 100, 3), dtype=np.uint8)
----> 7 av.VideoFrame.from_ndarray(img) # <- FAILS

av/video/frame.pyx in av.video.frame.VideoFrame.from_ndarray()

av/buffer.pyx in av.buffer.Buffer.update()

ValueError: got 100 bytes; need 31200 bytes
```

Minimal code reproducing the issue:
```python
import av
import numpy as np

img = np.zeros((100, 104, 3), dtype=np.uint8)
av.VideoFrame.from_ndarray(img) # <- OK
img = np.zeros((100, 100, 3), dtype=np.uint8)
av.VideoFrame.from_ndarray(img) # <- FAILS
```

I see the error with Python 2 and 3, in particular:
- Python 2.7.13 with av 6.0.0 and FFmpeg 3.4,
- Python 3.6.4 with av 6.1.0 and FFmpeg 3.4.

**Comment by jlaine** [comment]
The bogus error message has been fixed in HEAD, ("100 bytes" is wrong), but you are right there is an issue here:

- PyAV creates `VideoFrame` instances using alignment, as otherwise you are likely to get crashes when passing these frames to encoders
- the `from_ndarray` method blindly uses `Buffer.update` without taking into account the fact that the input is unaligned

**Comment by gatagat** [comment]
Yes, i can confirm it works. Tested on the two configs above.

Thanks!

**Comment by jlaine** [comment]
Excellent, thanks for reporting back, we often have "hit and run" bug reports, which aren't very satisfying!

**Comment by Mohitkumaraian** [comment]
Hey jlaine, Can you help me fix this issue? When I'm using VideoFrame.from_ndarray(img), I'm getting the following error:
File "av/video/frame.pyx", line 336, in av.video.frame.VideoFrame.from_ndarray
AssertionError

img is a ndarray of size (480,640) and stype = np.uint8

**Comment by jlaine** [comment]
Please don't hijack closed issues.
