### ISSUE TITLE
Buffering packet writes

### ISSUE THREAD

**Issue by alexhutnik** [PyAV-Org/PyAV#497]
I have a small number of separate rtsp streams being written to files. I simply loop over packets and mux them one by one.  Here is some simplified code:

```
source = av.open('rtsp://stream')
output = av.open('outputfile.mp4')
for p in source.demux():
    output.mux(p)
```

I _think_ that this is resulting in excessive disk IO. Even though these streams are relatively low bandwidth, disk access becomes very slow.  I've noticed that `htop` reports very high disk cache utilization.  I suspect performance could be improved by buffering a few MB worth of packets and flushing them to disk periodically.

Any advice?

OS: Linux
Python 3.6
PyAV 0.5.2
HDD: USB3 external hard drive

**Comment by jlaine** [comment]
Can you provide a full working example please, as things stand there is little we can do about this issue and will have to eventually close it.

**Comment by alexhutnik** [comment]
Turns out there were some impossible-to-find issues with the disk I was writing too. Closing issue.
