### ISSUE TITLE
Bug report| Frame drop and jump when decoding

### ISSUE THREAD

**Issue by iyah4888** [PyAV-Org/PyAV#526]
Frame jump and drop happens when I decode the video.

(Frame resolution) / PTS / Frame index
![image](https://user-images.githubusercontent.com/7327874/57895610-835e7800-781a-11e9-95c8-4df0a1f13e88.png)

This happens with the following option severely,
self.container.streams.video[0].thread_type = 'AUTO'
but I can mitigate a bit by commenting out the option.

(Frame resolution) / PTS / Frame index
![image](https://user-images.githubusercontent.com/7327874/57895668-dcc6a700-781a-11e9-9614-a2c13a8a226a.png)

A part of example code is as follow:
```
container = av.open(video_path)

video_stream = self.container.streams.video[0]

video_frames = []

for idx, frame in enumerate(container.decode(video=0)):

    video_frames.append(frame)

return video_frames
```

The actually generated frames were duplicated according to the frame index.
I think the frame indexes are correctly reported.

Test setting:
FFMPEG 4.0.2
PyAV 6.2.0
Python (anaconda) 3.6.7

[Example video](https://www.dropbox.com/s/ysk3q73xq2i6xdw/ewkFvB89_AE.00278244_00281414.mp4?dl=1) 
This is a part of AVSpeech dataset (This data is licensed by Google LLC under a Creative Commons Attribution 4.0 International License.)
I hope no copy right issue may be applied.

**Comment by fmassa** [comment]
If you look at the timestamps, you'll see that they are the same.

I think that this might just be a false sense of frame drop: in fact, the `frame index` that is returned is only approximate, and should not really be relied upon. For example, if you open the file once and read it two times, by seeking to the beginning of the file, you'll see that the frame indices won't be reset to zero, even though the frames will be decoded properly.

**Comment by mikeboers** [comment]
@fmassa If that is the case, then PyAV could and should fix it. It should be easy enough.
