### ISSUE TITLE
Release GIL for filters

### ISSUE THREAD

**Issue by ArtanisCV** [PyAV-Org/PyAV#527]
It seems that currently Filter Graph does not release GIL when pushing / pulling filtered frames. 

Is it possible to release GIL? The API for Filter Graph is quite complicated, and I am not sure where I can manually add the "with nogil" statement. Maybe here https://github.com/mikeboers/PyAV/blob/develop/av/filter/context.pyx#L107 ?

**Comment by NullYing** [comment]
Maybe here

https://github.com/mikeboers/PyAV/blob/5d192a13aabac9ec8eeea4cd9eee34558a3cabc3/av/filter/graph.pyx#L29

**Comment by mikeboers** [comment]
Both https://github.com/mikeboers/PyAV/blob/develop/av/filter/context.pyx#L80 and https://github.com/mikeboers/PyAV/blob/develop/av/filter/context.pyx#L107.

You'd need to do something like:

```
cdef int res
with nogil:
   res = do_the_thing()
err_check(res)
```
