### ISSUE TITLE
Create MISB Compilant video

### ISSUE THREAD

**Issue by All4Gis** [PyAV-Org/PyAV#533]
I wanted to know if this library allows to create a MISB video.
In other words, embed telemetry (KLV) in a new stream data / klv and create a new video. 

Is it possible with this library ,create and add new DataStream  on packet?

**Comment by tcdalton** [comment]
Bump on this. I assume this is blocked by #368 .

**Comment by All4Gis** [comment]
My last 5 cents to win this battle
https://gist.github.com/All4Gis/509fbe06ce53a0885744d16595811e6f
