### ISSUE TITLE
How can I find out what codec, format and extension combinations to use for output streams?

### ISSUE THREAD

**Issue by aspen1135** [PyAV-Org/PyAV#535]
I have been following some examples to figure out the decoding/encoding process with PyAV. What I have in the source code right now works, but it requires the user to specify a combination of codec, format and extension types that must be closely compatible with each other in order for it to not throw an exception.

With FFmpeg, I could just specify the output file extension, "some_file.wav" followed by "pcm_s8", and it would automatically convert the input file to a 8-bit .wav format file.

Given my example below, if I changed `pcm_s16le` to `pcm_s8`, it would throw an exception stating that the .wav extension type is not compatible with the given codec, despite FFmpeg having no problem at all automatically configuring the encoding/decoding process.

Is there a way to simply do this process without defining so many parameters? If not, where can I find the specific information about codec restraints and file-formats?

My goal is to specify an output file with the codec properties (ie. frame rate, bit depth) and extension type (like .wav or .mp3) in order to keep it as user-friendly and simple for the user as possible. Not many people, such as myself, will have common knowledge on encoders/decoders and types of PCM stuff.

```
def convert(path, codec, format, channel_layout, frame_rate):

    # set input/output locations

    inp = av.open(f"{path}SB-Kick 1.wav", 'r')
    out = av.open(f"{path}SB-Kick 2.wav", 'w')
    out_stream = out.add_stream(codec)


    # resampler object details how we want to change frame information
    resampler = av.AudioResampler(
        format=av.AudioFormat(format).packed,
        layout=channel_layout,
        rate=frame_rate
    )


    # decode frames and start re-encoding into new file
    for frame in inp.decode(audio=0):
        frame.pts = None  # pts is presentation time-stamp. Not relevant here.

        frame = resampler.resample(frame)  # get current working frame and re-sample it for encoding

        for p in out_stream.encode(frame):  # encode the re-sampled frame
            out.mux(p)

    out.close()


convert(path='C:/Users/Aspen/Google Drive/1. Software Engineering/Python/Samplify/',
        codec='pcm_s16le',
       format='s16',
       channel_layout='stereo',
       frame_rate=44100)
```

**Comment by jlaine** [comment]
As stated in the PyAV documentation, PyAV may not always be the right tool for the job. If the ffmpeg command line works for you, why not stick to it?

**Comment by aspen1135** [comment]
Dispatching a process 1 by 1 or threading them asynchronously is simply too slow when converting thousands of files.  I understand that these are bindings to the direct libraries but there should be another way to parse metadata and select a codec. Another user from the FFmpeg subreddit mentioned this when I asked there community:

> ffmpeg cli binary can do this - it uses the av_guess_codec() API call once it knows the output format, which is done automatically by the avformat library. I don't see PyAV having any reference to it, so you can't. Raise an issue with that project.

**Comment by mikeboers** [comment]
I can't imagine how you could get performance gains from PyAV vs. the `ffmpeg` command. I'd expect the `ffmpeg` command to generally be faster due to the lack of Python. Whatever job schedule you setup with PyAV will have an equivalent setup with the `ffmpeg` command.

I like the idea of using `av_guess_codec` in general, but I agree with @jlaine that PyAV may not be a good solution to this problem (which appears to be vanilla transcoding).

**Comment by aspen1135** [comment]
> I can't imagine how you could get performance gains from PyAV vs. the `ffmpeg` command. I'd expect the `ffmpeg` command to generally be faster due to the lack of Python. Whatever job schedule you setup with PyAV will have an equivalent setup with the `ffmpeg` command.
> 
> I like the idea of using `av_guess_codec` in general, but I agree with @jlaine that PyAV may not be a good solution to this problem (which appears to be vanilla transcoding).

I did lots of testing on this matter. Normally I would agree with you, and if the files I were testing were videos or long audio streams then maybe you would be right. However, when trying to convert an audio sample library consisting of 11,000 one-shot samples, it was estimating to take around 3 days (if I remember correctly) just to gather and parse the metadata information from Ffmpeg's ffprobe command. I tried a few different techniques, such as threading, dumping to files, and even using different terminal emulators in attempt to speed it up, but it was simply to slow. PyAV however, got this job done in under 60 seconds. The bottleneck was due to dispatching so many processes one by one.

So PyAV needs to be my primary back-end for audio conversation. I've learned more about codecs and their limitations. I'll probably need to make proper codec configurations for different extension types. And the extensions that are not commonly found or used could be routed into ffmpeg instead. That way the majority of the heavy-lifting is done by PyAV and I could retain a wide variety of file support.

The only way I see to specify a bit-depth during the encoding process is to use a codec that is specific to the bit-depth (i.e pcm_16le). Is there another way to specify the bits_per_sample? The AAC codec for example, allows you to adjust the sample-rate and bit-rate but not the bit-depth. An AAC file with a 32-bit depth could be compressed down further with no loss in audio fidelity if it were 24-bit instead.

I do not see an av_guess_format in the pyAV documents. Is there no python binding for it yet?

**Comment by mikeboers** [comment]
Heh. I'm glad I couched everything the way I did. Now I can imagine it. Thanks for your polite persistence. It is refreshing.

Anyways...

`av_guess_format` is not exposed. A part of the functionality must be used a bit lower down because when you specify a filename to `av.open` for writing FFmpeg does pick a format based on the extension.

If you need it explicitly, we could add either a `av.guess_format` or `av.ContainerFormat.guess` which takes `short_name`, `filename` and `mime_type` as kwargs.

`av_guess_codec` could be exposed in a few ways:

1. The format object can do it via `ContainerFormat.default_video_codec`/etc. attributes, or a `ContainerFormat.default_codec('video')` method.

2. `add_stream` could look for magic tokens `"__video__"` (or something else that reads better that won't conflict with real codecs).

I like the more explicit option 1. Also because then you can inspect the object without having to add it to a stream.

Re. bit depth. My understanding is that is set via the `AVCodecContext.sample_fmt`, which is exposed as the `CodecContext.format` attribute. You can set that to an `AudioFormat` or a string which identifies one.

I'm not eager to go on a big development adventure at this time, but if there is a clear way to add a single method or something somewhere that would make this all easier for you, I can likely do that.

**Comment by aspen1135** [comment]
Mike, I am eager to get this working but I am still somewhat new to this library so please excuse my ignorance. I tried to find a way to exposing the `av_guess_codec` with both methods you suggested but I am not able to find `default_video_codec` or a clear way to set `"__video__"` tags.

While attempting to figure out the bit-depth thing, I did something like this within the resampler:
`format=av.AudioFormat.format(*bit-depth goes here as int*)`

But it says .format does not exist as part of AudioFormat.

Maybe you could provide a small example?

```
def convert(input, output, file_name, extension, codec, channel_layout, frame_rate):

    try:
        # set input/output locations
        inp = av.open(f"{input}", 'r')
        out = av.open(f"{output}/{file_name}{extension}", 'w')
        out_stream = out.add_stream(f"{codec}")


        # resampler object details how we want to change frame information
        resampler = av.AudioResampler(
            format=av.AudioFormat.format,  # "Unresolved reference 'format' for class 'AudioFormat'
            rate=frame_rate,
            layout=channel_layout,
        )


        # decode frames and start re-encoding into new file
        for frame in inp.decode(audio=0):
            frame.pts = None  # pts is presentation time-stamp. Not relevant here.

            frame = resampler.resample(frame)  # get current working frame and re-sample it for encode

            for p in out_stream.encode(frame):  # encode the re-sampled frame
                out.mux(p)

            # max_bit_rate

        out.close()


    except Exception as e:
        App_Settings.exception_counter = App_Settings.exception_counter + 1   # 'Files failed: '
        logger.info('Could not convert the file.'
                    ''
                    f'{e}')
```

**Comment by aspen1135** [comment]
@mikeboers 

A small update to the issue.

**guess_codec**
I got my program to automatically identify the output codec by sending the file type into FFmpeg initially, then cataloging that information into my programs database for future reference. This way if it runs across the extension type again, it can then specify to the output stream what codec needs to be used. Seems to be working great so far and minimizes the performance impact of relying on FFmpeg from a shell. I unfortunately still could not expose the av_guess_codec function as you said.

**changing bit-depth:**
I also got the bit-depth conversion working by specifying the resamplers 'format' argument to an accepted a string format ( ie. `s16` ). I owe you a big thanks dude. I was just too stupid to realize to understand what needed to be passed at first and figured it out after playing around FFmpeg's shell.

There is still another small issue with the method to specify the bit-depth however. FFmpeg's supported sample_fmts are in only 8, 16 32, and 64 and there is nothing for 24 bit. It seems that for wav files you could easily do it by using the corresponding encoder `pcm_s24le` but for some file types that option is not available. There has been some discussion about the topic [here](uhttps://stackoverflow.com/questions/29131173/how-to-encode-24-bit-audio-with-libav-ffmpegrl) describing a situation where others have encountered this problem with FLAC audio files. FLAC's should support 24 bit and even PCM raw audio but FFmpeg requires a little further lower-level configuration with some additional flags to do so.

It seems there is a way to do it within AVCodecPerameters using `bits_per_raw_sample` but I did not see any references similar to this in PyAV's codec classes. Could we maybe expect to see this `bits_per_raw_sample` binding within PyAV's library in the near future..?

I have a workaround to this issue for my own applications, although it's not an ideal one and is kind of hacky. I can change the output encoder to pcm_s24le when a user specifies an output extension that is not a lossy format (since bit-depth is disregarded anyway), and the few formats that don't accept that kind of encoder could then be fed straight to an FFmpeg shell in order to do the conversion with the additional flags.

But again- the purpose of me using this library for my project was to improve performance for batch processes. Anytime I run a large quantity of media files into into FFmpeg instead of PyAV, it literally cuts my performance speed **_in half_** and takes twice as long or more.

It would be fantastic to have a PyAV solution for this.
