### ISSUE TITLE
write to v4l2 device

### ISSUE THREAD

**Issue by yousifa** [PyAV-Org/PyAV#536]
Hi,

How can I use av.open(..) to write to a v4l2 device (eg. /dev/video1)? I've only been able to read from it and see no examples of writing to it.

**Comment by jlaine** [comment]
You can try:

`with av.open("/dev/video1") as container:
    container.add_stream("rawvideo")
    ...
`

**Comment by yousifa** [comment]
I had to increase the framerate to a higher number (fps=31 instead of 30, which is what it should be). Or else, I was getting the following error after 5-10sec:
`Application provided invalid, non monotonically increasing dts to muxer in stream 0` 

Any thoughts on a non-hacky way to fix this?

**Comment by mikeboers** [comment]
Were you providing monotonically increasing dts to the muxer? 😛

**Comment by yousifa** [comment]
> You can try:
> 
> ```
> with av.open("/dev/video1") as container:
>     container.add_stream("rawvideo")
>     ...
> ```

thats exactly what I was doing

**Comment by yousifa** [comment]
> Were you providing monotonically increasing dts to the muxer? 😛

I'm not sure.. the stream is coming from a webcam stream via aiortc. How can I find out?

**Comment by mikeboers** [comment]
Seems like some assumption somewhere might be a bit broken. My feeling is that in this case you shouldn't be needing to manually set `pts/dts` on things, but... don't know.

Try printing out the `Frame.pts` and `Packet.dts` in both directions and see if they make sense. Then at least we can see if the error is correct, and work back from there.

**Comment by jlaine** [comment]
@yousifa ping?

**Comment by yousifa** [comment]
Sorry, I don't have time to test this further right now. I was never able to get this fixed.
