### ISSUE TITLE
Seek to frame in mkv must by multiplied by 1000 / framerate

### ISSUE THREAD

**Issue by pfk-beta** [PyAV-Org/PyAV#569]
## Overview
I was experimenting with seeking to certain moment of movie. After many tries-and-fails I've got value, which should I use to multiply frame number to get proper place of movie - 42. Which is in my situation 1000 divided by 23.97

## Expected behavior
When I call 
```python
in_container.seek(5000, whence='frame', stream=in_stream)
```
I would like to get movie in more or less proper place without math calculations

## Actual behavior
It is working, but incorrect

## Versions

- OS: ubuntu docker
- PyAV runtime: '6.2.0'

PS
I there a way, to get absolute frame index after usage of `seek`?

**Comment by pfk-beta** [comment]
thank you

**Comment by jlaine** [comment]
We only support seeking by time nowadays, closing.
