### ISSUE TITLE
RTSP stream returns negative PTS if running for a long time

### ISSUE THREAD

**Issue by alexhutnik** [PyAV-Org/PyAV#591]
When I open an RTSP from an IP camera and let it run for a long time, at some point the pts will come through as a negative number.  I suspect there is an integer overflow happening in the camera but I'm not sure what to do about it. Since other PyAV users might be using RTSP streams in a similar manner (i.e. long running video recording / surveillance), I wonder how others have handled this?

**Comment by jlaine** [comment]
Did you ever get to the bottom of this? Is this actually a PyAV issue or is it in the underlying FFmpeg libraries?

**Comment by jlaine** [comment]
Duplicate of #78
