### ISSUE TITLE
Warn that we no longer support FFmpeg 3.x

### ISSUE THREAD

**Issue by mikeboers** [PyAV-Org/PyAV#605]
I'm not sure how, but it would be really nice to do this. See #603 and #604.

**Comment by DurandA** [comment]
Also, it would be nice to update the [docs for Ubuntu >= 18.04 LTS](https://github.com/mikeboers/PyAV/blob/develop/docs/overview/installation.rst#ubuntu--1804-lts) as 18.04 comes with FFmpeg 3.4.6.

**Comment by mikeboers** [comment]
OOookay. I finally feel compelled that I need to do *something*. I'm thinking at a minimum adding a compile-time error that checks against the library versions to absolutely assert it is building against the version we think it is.

**Comment by mikeboers** [comment]
If it is trivial, e.g. just a couple of constants not working, I'll re-add 3x support. But I don't think it is trivial.

**Comment by jlaine** [comment]
I'd say goodbye FFmpeg 3.x, it's hard enough maintaining the project as is..

**Comment by mikeboers** [comment]
@jlaine Thanks for the vote.

I'm just trying to figure out the macOS tests on GA, and then this warning will be rolled out.

**Comment by jlaine** [comment]
I'm closing this, doesn't seem worth the hassle
