### ISSUE TITLE
Python ssl module missing on macOS GitHub Actions

### ISSUE THREAD

**Issue by mikeboers** [PyAV-Org/PyAV#624]
I'm not quite sure how to fix this.

This is blocking merging #605.

**Comment by jlaine** [comment]
Aw damn it, I was just getting comfortable with the idea that GItHub Actions was superior to Travis in every way..

**Comment by jlaine** [comment]
AFAICT this is the issue tracking this problem: https://github.com/actions/setup-python/issues/83

**Comment by mikeboers** [comment]
> Aw damn it, I was just getting comfortable with the idea that GItHub Actions was superior to Travis in every way..

I'm pretty sure Travis gave us much more trouble on macOS. The first setup on GA here was really smooth. And, that there is somewhere to open issues against these things is really nice.

So... I maintain it remains superior in every way. It just isn't perfect. But that is too high a bar.

In the meantime, since I'm on macOS, I'm thinking of making these tests not fail the whole suite. I'd really like to release 7.0.2 with the FFmpeg >=v4 test (and this failing is stopping me).

**Comment by jlaine** [comment]
I'm not seeing these errors on all my repos, so I'm wondering if we're doing something to the environment variables (e.g.: touching DYLD_LIBRARY_PATH) which is triggering this.

On a related note: the `activate.sh` script confuses the hell out of me, and I think it's adding more confusion than it actually helps: is it only for CI? Is it for general consumption?

**Comment by mikeboers** [comment]
I cleaned up `activate.sh` and all of the scripts a bit to remove old Travis and Vagrant stuff, and clarify with some more comments.

It is there to setup the development environment. Put things in the right places, etc..

**Comment by jlaine** [comment]
I'd argue there isn't much to "put in the right place", you'll probably have noticed that our jobs to create binary wheels + execute the test suite on them don't rely on `activate.sh` at all!

**Comment by mikeboers** [comment]
It serves more of a purpose for my while developing against multiple Python version and multiple FFmpeg versions, and keeping that nicely in a row. I can see how all of the CI could be done without it.

**Comment by mikeboers** [comment]
Answering a question much higher...

> I'm not seeing these errors on all my repos, so I'm wondering if we're doing something to the environment variables (e.g.: touching DYLD_LIBRARY_PATH) which is triggering this.

I don't think `activate.sh` would affect that, but I'll try!

**Comment by jlaine** [comment]
It would seem the culprit might be homebrew: https://github.com/actions/setup-python/issues/83#issuecomment-623435822

**Comment by jlaine** [comment]
This doesn't seem to be an issue anymore
