### ISSUE TITLE
Double freeing CodecContext.extradata?

### ISSUE THREAD

**Issue by mikeboers** [PyAV-Org/PyAV#640]
See [this comment](https://gitter.im/mikeboers/PyAV?at=5ea1dba61e3d5e20633cd8a5)

**Comment by jlaine** [comment]
Yeah the memory ownerships looks very dodgy here. A `memcpy` seems like a reasonable idea.

**Comment by haohuanw** [comment]
https://github.com/PyAV-Org/PyAV/pull/658#issue-412365032
pr for fixing this issue; I have applied this patch and tested with my offline use case and it works well.

**Comment by jlaine** [comment]
To the best of my knowledge this was fixed in #756
