### ISSUE TITLE
Consolidate PyAV packages/etc.

### ISSUE THREAD

**Issue by mikeboers** [PyAV-Org/PyAV#647]
Perhaps, we ought to move this and the ffmpeg wheel repo under a new PyAV organization (I grabbed PyAVorg, although PyAV-org might be nicer), and move the docs to `pyav.org/docs` (which I just bought).

**Comment by jlaine** [comment]
If you add me to the new org I will happily transfer the `pyav-ffmpeg` repo there.

**Comment by mikeboers** [comment]
Done.
