### ISSUE TITLE
How do I FOO?

### ISSUE THREAD

**Issue by jin-github1002** [PyAV-Org/PyAV#651]
I used these command to install ffmpeg
dell@dell-XPS-15-9550:~$ sudo apt-get install -y python-dev pkg-config
(base) dell@dell-XPS-15-9550:~$ sudo apt-get install -y libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libswresample-dev libasfilter-dev

then 
pip install av
failed. i have python2.7and python3 in the computer.
Then ,i tried to install av
(base) dell@dell-XPS-15-9550:~/PyAV$ sudo python3 setup.py build_ext --inplace --debug
running build_ext

the error in the end is:
src/av/codec/codec.c: In function ‘__pyx_f_2av_5codec_5codec_get_codec_names’:
src/av/codec/codec.c:3937:19: warning: implicit declaration of function ‘av_codec_iterate’; did you mean ‘av_codec_next’? [-Wimplicit-function-declaration]
     __pyx_v_ptr = av_codec_iterate((&__pyx_v_opaque));
                   ^~~~~~~~~~~~~~~~
                   av_codec_next
src/av/codec/codec.c:3937:17: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
     __pyx_v_ptr = av_codec_iterate((&__pyx_v_opaque));
                 ^
src/av/codec/codec.c: In function ‘__pyx_pymod_exec_codec’:
src/av/codec/codec.c:6031:36: error: ‘AV_CODEC_CAP_HARDWARE’ undeclared (first use in this function); did you mean ‘AV_CODEC_CAP_DR1’?
   __pyx_t_7 = __Pyx_PyInt_From_int(AV_CODEC_CAP_HARDWARE); if (unlikely(!__pyx_t_7)) __PYX_ERR(0, 121, __pyx_L1_error)
                                    ^~~~~~~~~~~~~~~~~~~~~
                                    AV_CODEC_CAP_DR1
src/av/codec/codec.c:6031:36: note: each undeclared identifier is reported only once for each function it appears in
src/av/codec/codec.c:6052:36: error: ‘AV_CODEC_CAP_HYBRID’ undeclared (first use in this function); did you mean ‘AV_CODEC_CAP_DR1’?
   __pyx_t_7 = __Pyx_PyInt_From_int(AV_CODEC_CAP_HYBRID); if (unlikely(!__pyx_t_7)) __PYX_ERR(0, 125, __pyx_L1_error)
                                    ^~~~~~~~~~~~~~~~~~~
                                    AV_CODEC_CAP_DR1
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

the version of ffmpeg is:

(base) dell@dell-XPS-15-9550:~$ ffmpeg -version
ffmpeg version 4.1.3 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 7.3.0 (crosstool-NG 1.23.0.449-a04d0)
configuration: --prefix=/home/dell/anaconda2 --cc=/home/conda/feedstock_root/build_artifacts/ffmpeg_1556785800657/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc --disable-doc --disable-openssl --enable-avresample --enable-gnutls --enable-gpl --enable-hardcoded-tables --enable-libfreetype --enable-libopenh264 --enable-libx264 --enable-pic --enable-pthreads --enable-shared --enable-static --enable-version3 --enable-zlib --enable-libmp3lame
libavutil      56. 22.100 / 56. 22.100
libavcodec     58. 35.100 / 58. 35.100
libavformat    58. 20.100 / 58. 20.100
libavdevice    58.  5.100 / 58.  5.100
libavfilter     7. 40.101 /  7. 40.101
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  3.100 /  5.  3.100
libswresample   3.  3.100 /  3.  3.100
libpostproc    55.  3.100 / 55.  3.100

MYABE i have to ues python3 because there are 2-3 versions of python in my computer.

Does anybod know how to solve it?

I will appreciate your help. Thank you so much 
---------------------------------------------------------------------

**Comment by jlaine** [comment]
- Python2 is no longer supported.

- The compiler errors show you're linking against old FFmpeg *libraries*. My guess is that you have multiple FFmpeg on your system and the build is picking up the old one.

- if I were you I would not compile as root.

You should be able to install PyAV in the form of binary wheels with zero compilation. If it's not working your `pip` is probably out of date.

Here is how to install PyAV in a fresh virtual environment:

```
sudo apt install python3-venv
python3 -m venv env
source env/bin/activate
pip install -U pip
pip install av
```

**Comment by jin-github1002** [comment]
ya, it really works! But my tello python can not run yet. it says can not import cv2.cv2.  Could you please help? @jlaine thank you so much!

**Comment by jlaine** [comment]
`pip install opencv-python`

**Comment by jin-github1002** [comment]
> `pip install opencv-python`

yes. It works! Thank you.
