### ISSUE TITLE
Upload docs from GitHub Actions

### ISSUE THREAD

**Issue by mikeboers** [PyAV-Org/PyAV#656]
What the title says.

The docs are currently hosted on one of my personal servers. Any sort of authenticated deployment is acceptable to me. I'm open to writing a tiny Flask app to assist which manages the versioning as well.

**Comment by mikeboers** [comment]
Seems like this might be the most reasonable way to authenticate: https://github.com/marketplace/actions/install-ssh-key

That SSH key could/should be restricted to a small script that deals with versioning.

**Comment by jlaine** [comment]
It sort of scares me that I could accidentally nuke your server, I'm not sure SSH'ing into your server is a good fit for the public nature of the project.

I see two options:

- host the docs on readthedocs. I know you mentioned you have some custom logic going on, but sphinx is really very extensible

- have Github Actions deliver a trigger to your server (with a secret managed in the projects' "secrets") to an HTTP endpoint which actually performs the docs build

**Comment by mikeboers** [comment]
You can easily restrict a SSH key to only be able to run a single command. That command could accept a tarball of the docs build. I'm not concerned at all TBH.

Could do readthedocs if we can upload a built version.

**Comment by jlaine** [comment]
This is till a goal

**Comment by jlaine** [comment]
This is still a goal
