### ISSUE TITLE
Incorrect audio length of AAC file

### ISSUE THREAD

**Issue by kice** [PyAV-Org/PyAV#663]
**It looks like I am doing transcode, but I AM NOT.**
```python
import av
import soundfile as sf

data, sample_rate = sf.read('something.wav')
n_samples = data.shape[0]
n_channels = data.shape[1]

container = av.open('test.aac', 'w')
stream = container.add_stream('aac', rate=sample_rate)

stream.open()
time_base = stream.codec_context.time_base
frame_size = stream.codec_context.frame_size

stride = frame_size * n_channels

data = data.reshape(1, -1)
for i in range(0, n_samples * n_channels, stride):
    frame = av.AudioFrame.from_ndarray(data[:, i:i+stride], 'dbl')
    frame.sample_rate = sample_rate
    frame.time_base = time_base
    frame.pts = i // n_channels

    container.mux(stream.encode(frame))

container.mux(stream.encode())
container.close()
```

I am using Numpy to generate audio file and want to use PyAV to encode as AAC file. ~~It is the same format as I open the file with PySoundFile.~~

The file could be generated but my player shows incorrect audio length. I have a 5 second audio, but it shows the AAC file form PyAV is 51 seconds long.

Btw, if I remove the two lines shown in below, 
```
    frame.time_base = time_base
    frame.pts = i // n_channels
```
ffmpeg will complain `Encoder did not produce proper pts, making some up.`

**Comment by jlaine** [comment]
Please provide your input file, as we don't have enough to go on here.

**Comment by kice** [comment]
I just forgot raw aac requires a container to work with players. In this case I use m4a. 

Thanks for your response anyway.
