### ISSUE TITLE
Creating UDP broadcast socket with audio packets (client/server sides)

### ISSUE THREAD

**Issue by riccardobrue** [PyAV-Org/PyAV#669]
Hi, I have to create a audio streaming system which captures audio from my PC mic and sends UDP packets to WebRTC peers (I am using aiortc). What I have done so far has been creating a peer with a MediaPlayer (which relies on PyAV) to capture the audio from the microphone, but when another peer connects to the "room" the PyAV library tells me that the ALSA is busy. So I was thinking to instead or creating instances of players which capture the mic audio directly, to have a single audio capture server which broadcasts in localhost UDP packets, then several UDP clients are open to catch those packets (something like av.open("udp://localhost:6000")). My question is if there is a better approach to do this task. And if this is actually the only one solution, how to create the server and client sides:
- The PyAV server captures the audio from the microphone and sends UDP packets.
- The PyAV clients connects to the local port and decode the sent audio UDP packets.

**Comment by jlaine** [comment]
I understand you're looking for someone to do the work for you, but opening a ticket both against `aiortc` and `PyAV` isn't going to help.
