### ISSUE TITLE
Allow conversion from `VideoFrame` in 'gray16be' or 'gray16le' pixel format to ndarray

### ISSUE THREAD

**Issue by LHolten** [PyAV-Org/PyAV#674]
## Overview

Currently when trying to run code like `frame.reformat(format='gray16').to_ndarray()` an error is thrown `ValueError: Conversion to numpy array with format 'gray16le' is not yet supported`.

## Desired Behavior

`frame.reformat(format='gray16').to_ndarray()` should return a numpy array with dtype `numpy.uint16`.

## Example API

```python
with av.open(path) as container:
    for frame in container.decode(video=0):
        yield frame.reformat(format='gray16').to_ndarray()
```

## Additional context

In my current project I need to convert video frames to grayscale, but 'gray8' doesn't have enough depth.

**Comment by jlaine** [comment]
Sure feel free to submit a PR I'll be happy to review it. Make sure you include unit tests in `TestVideoFrameNdarray`, which is found in `tests/test_videoframe.py`

**Comment by tbenst** [comment]
@jlaine I might be able to take a crack at this (although my interest is more in `gray10le`. Looks like the relevant code is in https://github.com/PyAV-Org/PyAV/blob/6f9a1561f43e0cedc10c0ee33cd30bded7d34dc0/av/video/frame.pyx#L296. Could you by chance give me a high level overview of where I’ll need to change things?
