### ISSUE TITLE
How do I add https protocol?

### ISSUE THREAD

**Issue by vinnitu** [PyAV-Org/PyAV#675]
I need av.open https links
How to properly rebuild ffmpeg shared libraries (in av.libs) to add https protocol support?

Trying add --enable-openssl --enable-nonfee to scripts/build-deps but without success 
Have a centos7

I discover av-8.0.1-cp36-cp36m-manylinux2010_x86_64.whl

and saw
![image](https://user-images.githubusercontent.com/432168/83133181-23680600-a0eb-11ea-910c-13e0ab17ed44.png)

how do you build this?

![image](https://user-images.githubusercontent.com/432168/83133092-016e8380-a0eb-11ea-9f3b-d571e60b95eb.png)

how do you pack it in whl?

I trying use 
```
source scripts/acrivate.sh
scripts/build-deps
```
but see my result in right panel 

![image](https://user-images.githubusercontent.com/432168/83133461-970a1300-a0eb-11ea-8e62-590588ca719e.png)

**Comment by vinnitu** [comment]
can you add gnutls or openssl to your next build?

**Comment by jlaine** [comment]
Thanks for reporting this! If you have time, could you try submitting a PR against this repo, which is where we build the FFmpeg binaries:

https://github.com/PyAV-Org/pyav-ffmpeg

**Comment by jlaine** [comment]
I've started a PR for this here: https://github.com/PyAV-Org/pyav-ffmpeg/pull/10

**Comment by jlaine** [comment]
Could you give the attached wheel a try please, it's built with GnuTLS support.

NOTE: I've had to put it in a ZIP file as github doesn't accept .whl files directly
[av-8.0.2.dev0-cp36-cp36m-macosx_10_9_x86_64.whl.zip](https://github.com/PyAV-Org/PyAV/files/4715758/av-8.0.2.dev0-cp36-cp36m-macosx_10_9_x86_64.whl.zip)

**Comment by vinnitu** [comment]
av.libs is misssing in this .whl?

**Comment by jlaine** [comment]
The libraries are present in `av/.dylibs`. Could you please focus on the high level test (which I cannot do myself) : does it work?

**Comment by jlaine** [comment]
Ah crap, my mistake I sent you Mac OS wheel!! Here is the one for Linux:

**Comment by jlaine** [comment]
My mistake, I sent you a Mac OS wheel. I'm unfortunately unable to send the Linux one as github complains the file is too big..

**Comment by vinnitu** [comment]
thank you very much

**Comment by jlaine** [comment]
You're welcome!

**Comment by vinnitu** [comment]
seams it doesn't work on other machines (maybe my pc have needed files already after my own experimentes)

```python
import av

av.open('https://ichef.bbci.co.uk/images/ic/960x960/p08634k6.jpg')
# Illegal instruction (core dumped)
```

**Comment by M-A-N-I-S-H-K** [comment]
Hey @jlaine 
I tried to install it on ubuntu18.04 with python version 3.6/3.7  with `pip install av==8.0.1 --no-binary av`  but it keeps failing.
These are the packages I have installed on docker 
```python-dev pkg-config \
   libavformat-dev libavcodec-dev libavdevice-dev \
   libavutil-dev libswscale-dev libswresample-dev libavfilter-dev \
   autoconf automake build-essential cmake \
   libass-dev libfreetype6-dev libjpeg-dev libtheora-dev \
   libtool libvorbis-dev libx264-dev \
   pkg-config wget yasm zlib1g-dev libpq-dev
```

Is there something I am missing ?

When I do a simple install of pyav==8.0.1 , https stream does not work.
