### ISSUE TITLE
Allow Packet.is_keyframe to writable

### ISSUE THREAD

**Issue by shersonb** [PyAV-Org/PyAV#678]
## Overview

Allow the keyframe flag of 'Packet' objects be modified.

## Desired Behavior

To be able to set the keyframe flag of av.Packet objects. When muxing packets from a source other than PyAV, one must create a Packet instance containing packet data, as well as setting the pts and time_base attributes. However, there is currently no way to modify the keyframe flag.

## Example API

```python
# Assume 'packets' is a list or iterator of objects (containing data, pts, and keyframe attributes), and these packets are to be muxed to a file using PyAV. These packets must be converted to av.Packet objects.

for packet in packets:
    avpacket = av.Packet(packet.data) # This works
    avpacket.pts = packet.pts # This works.
    avpacket.is_keyframe = packet.keyframe # This fails.
    output_container.mux(avpacket)

```

## Additional context

I am currently writing a matroska module that allows for access to all features currently supported by the matroska file format. It currently has muxing and demuxing capabilities and has its own internal Packet class. Allowing av.Packet.is_keyframe would allow for converting back and forth between the two Packet classes.

**Comment by jlaine** [comment]
Feel free to submit a PR.
