### ISSUE TITLE
seams it doesn't work on other machines (maybe my pc have needed files already after my own experimentes)

### ISSUE THREAD

**Issue by vinnitu** [PyAV-Org/PyAV#685]
seams it doesn't work on other machines (maybe my pc have needed files already after my own experimentes)

```python
import av

av.open('https://ichef.bbci.co.uk/images/ic/960x960/p08634k6.jpg')
# Illegal instruction (core dumped)
```

_Originally posted by @vinnitu in https://github.com/PyAV-Org/PyAV/issues/675#issuecomment-645971654_

**Comment by jlaine** [comment]
Works fine for me, I used:

```
import av

with av.open('https://ichef.bbci.co.uk/images/ic/960x960/p08634k6.jpg') as container:
    for packet in container.demux():
        for frame in packet.decode():
            print(frame)
```

I'm not sure why you would want to use PyAV to retrieve a JPEG though to be honest..
