### ISSUE TITLE
How do I write to a v4l2loopback device?

### ISSUE THREAD

**Issue by kno10** [PyAV-Org/PyAV#691]
ffmpeg can write to v4l2loopback devices, e.g., `ffmpeg -y -f bmp_pipe -i - -f v4l2 /dev/video4`

But when I try to open a v4l2 device for writing with PyAV I always get the error
```
    container = av.open(outdev, mode="w", format="v4l2")
  File "av/container/core.pyx", line 363, in av.container.core.open
  File "av/container/core.pyx", line 145, in av.container.core.Container.__cinit__
ValueError: Could not determine output format
```

**Comment by jlaine** [comment]
It looks as though there is a bug here:

https://github.com/PyAV-Org/PyAV/blob/359dbbdcd2fe8816d1d2eb3f9b67993da44d33cb/av/format.pyx#L183

Some formats go by multiple names, in which case they seem to be comma-separated. In the case of video4linux2 the "name" seems to be : `"video4linux2,v4l2"`
