### ISSUE TITLE
ValueError: whence != 'time' is no longer supported

### ISSUE THREAD

**Issue by rmiranda13** [PyAV-Org/PyAV#696]
I'm trying to use a tracking software which can take a video file as an input in place of a camera. However, whenever I try to run it on my desktop the feed plays a single image instead of a video, and I receive the following errors: 

File "C:\Users\Work\anaconda3\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\Work\anaconda3\lib\site-packages\stytra\hardware\video\__init__.py", line 362, in run
    container.seek(0, whence="frame")
  File "av\container\input.pyx", line 232, in av.container.input.InputContainer.seek
ValueError: whence != 'time' is no longer supported

The video file works just fine with the same setup I have on my other machine, but can't find any notable differences in the environment. Is this error something you've come across before? Google doesn't seem to pull anything up, but I'm suspecting it's some issue occuring with av. Thank you!

**Comment by jlaine** [comment]
This syntax for `seek` is no longer support since PyAV 7.0.0, see the changelog:

https://github.com/PyAV-Org/PyAV/blob/main/CHANGELOG.rst#v700
