### ISSUE TITLE
Allow user to force audio codec to be used instead of relying the default one

### ISSUE THREAD

**Issue by Kazhuu** [PyAV-Org/PyAV#702]
## Overview

Regarding [this](https://github.com/PyAV-Org/PyAV/issues/699) issue of mine earlier. Would it be possible to expose field `AvFormatContext::audio_codec_id` for user to force specific audio codec?

## Existing FFmpeg API

Documentation of the field [here](https://ffmpeg.org/doxygen/3.3/structAVFormatContext.html#ab179ade0dbe905ab2867b7001bf618ec).

## Expected PyAV API

Maybe add this to `av.open()` to be optional argument.

Example:
```
av.open('alsa-device', format='alsa', audio_codec='pcm_s32le')
```

I could also take this one and make contribution to this awesome library if this is considered something needed in general. Any thoughts?

**Comment by paulhobbel** [comment]
Any news on the implementation of this?

**Comment by Kazhuu** [comment]
Sorry but I have been busy with so many other things and haven't have time/interest for this one at the moment. Maybe someone else can give this a go instead. I tried to start implementing this but then soon realized that there are so many available codecs that left me wondering should all them be implemented or just selected few.

**Comment by paulhobbel** [comment]
I'm currently trying out your solution but am failing to buil PyAV on my raspberry pi. Do you have any tips on how I can build PyAV?

**Comment by Kazhuu** [comment]
I don't remember the steps out of my head but I think I was needing this package for one of my projects. I cloned it to my project and installed the package from there to my python virtual environment using `pipenv install -e ext/PyAV`. Then I just modified the sources in place. Of course you need to install Cython and other required packages to build the package. From readme the requirements are installed with `pip install --upgrade -r tests/requirements.txt`. Hope those helps.

**Comment by Kazhuu** [comment]
@paulhobbel I made a PR of this [here](https://github.com/PyAV-Org/PyAV/pull/816)

**Comment by Kazhuu** [comment]
I've a holiday coming weeks I could take a look at this.

**Comment by Kazhuu** [comment]
ping

**Comment by Kazhuu** [comment]
Is this still valid?
