### ISSUE TITLE
Support for ARM binary wheels (aarch64)

### ISSUE THREAD

**Issue by matheus2740** [PyAV-Org/PyAV#708]
## Overview

Availability of aarch32 and aarch64 pre-built binary wheels

## Desired Behavior

`pip install av` should not have to compile/depend on ffmpeg libs on ARM.

## Example API

```
N/A
```

## Additional context

I'm currently deploying a solution in multiple arm devices (in which the OS is out of my control), and installing ffmpeg 4 in older versions of ubuntu (14.04, 16.04, sometimes 18.04) is proving quite a challenge. Having pre-built wheels for ARM with ffmpeg 4 bundled would be a life saver.

I'm willing to help and even implement this myself, but I need some initial guideance on how to get started.

**Comment by jlaine** [comment]
aarch32 is going to remain out of scope as only aarch64 is specified in the manylinux2014 PEP:

https://www.python.org/dev/peps/pep-0599/

I'll give aarch64 a shot.

**Comment by jlaine** [comment]
The first step towards providing wheels for aarch64 is to have a built of FFmpeg and all its dependencies, as is done here:

https://github.com/PyAV-Org/pyav-ffmpeg

However I have tried and the build repeatedly fails, it seems to time out. Until that's solved I can't do much more..

**Comment by golyalpha** [comment]
Just to note, #830 and #824 talk about ARMv7 support - aarch64 is 64bit ARMv8
