### ISSUE TITLE
Allow PyAV to export motion vector map

### ISSUE THREAD

**Issue by SuX97** [PyAV-Org/PyAV#715]
**IMPORTANT:** Be sure to replace all template sections {{ like this }} or your issue may be discarded.

## Overview

{{ Hi, I have noticed that there are not usage example of how to get the motion vector, and the only clue I have got lies [here](https://github.com/PyAV-Org/PyAV/blob/main/tests/test_decode.py#L53) in the unittest. Could you please show a standard and efficient usage of transfer a motion vector into a mv map? Namely the motion offset of each pixel, a matrixs of size (2, height, weight)?

A simple implementation can be [this](https://github.com/chaoyuaw/pytorch-coviar/blob/master/data_loader/coviar_data_loader.c#L97), but it use a nested loop on each pixel, seems inefficient. }}

## Desired Behavior

{{ 
```
    def test_decoded_motion_vectors(self):

        container = av.open(fate_suite('h264/interlaced_crop.mp4'))
        stream = container.streams.video[0]
        codec_context = stream.codec_context
        codec_context.options = {"flags2": "+export_mvs"}

        for packet in container.demux(stream):
            for frame in packet.decode():
                vectors = frame.side_data.get('MOTION_VECTORS')
                vectors_map = frame.side_data.parse_mv(vectors)# TODO
                if frame.key_frame:
                    # Key frame don't have motion vectors
                    assert vectors is None
                else:
                    assert len(vectors) > 0
                    return
```
}}

## Example API

```
{{
def parse_mv(vector) -> np.ndarray:
Args:
    vector: np.ndarray, [(-1, src_x, src_y, dst_x, dst_y, motion_x, ...), ()..]
Returns:
    np.ndarray: of shape (2, h, w) 
}}
```

## Additional context

{{ Add any other context about the problem here. }}

**Comment by YuqiHUO** [comment]
hi, im interested in this feature, what do you think of two-source of [-1] and [+1] of B-frames? does it need to return two mv maps of the previous and the next frame?

**Comment by wuhy08** [comment]
I think you can use `vector.to_ndarray()` to extract it

**Comment by mfoglio** [comment]
Any update on this? Is there a way to extract motion vectors without decoding an RSTP stream?
