### ISSUE TITLE
Allow other libraries to `cimport av`

### ISSUE THREAD

**Issue by papr** [PyAV-Org/PyAV#716]
## Overview

I would like to build a Cython extension that imports and uses pyav's Cython classes. [Cython recommends modules to distribute their `*.pxd` files as `package_data`](https://cython.readthedocs.io/en/latest/src/userguide/sharing_declarations.html#search-paths-for-definition-files) to allow other packages to cimport items from your module as a dependency.

## Desired Behavior

Please distribute your pxd files, including those in `include/`, within your module.

## Example API

```cython
cimport av
```

## Additional context

We have previously [forked pyav](https://github.com/pupil-labs/pyav) to add our own features. Unfortunately, it is not easily possible to rebase our changes on top of the current version. Instead, we would like to extract our changes into a separate module that depends on your pyav version.

[There is precedence in regards to distributing pxd based on this method.](https://github.com/zeromq/pyzmq/blob/master/setup.py#L1292-L1297)

**Comment by papr** [comment]
It also seems to be a common pattern [to implement a `get_includes()` function](https://github.com/zeromq/pyzmq/blob/master/zmq/__init__.py#L60-L68) that can be passed to `setuptools.Extension`'s `include_dirs` argument.

**Comment by jlaine** [comment]
Does this change our API surface, i.e. does it change what members of classes are made available to API users?

**Comment by papr** [comment]
Hi @jlaine, thanks for taking the time to have a look at this.

The python api would not be affected.

Including the pxd files allows other packages to subclass pyav's Cython classes in Cython http://docs.cython.org/en/latest/src/userguide/extension_types.html#subclassing

I guess that means creating a new API surface.

**Comment by jlaine** [comment]
Fixed in 1b709194a40a0285068260f240d7bf3efc720ea7
