### ISSUE TITLE
Binary wheels for Python 3.9

### ISSUE THREAD

**Issue by amotl** [PyAV-Org/PyAV#734]
Dear @mikeboers and @jlaine,

first things first: Thanks a stack for conceiving and maintaining the excellent PyAV package.

It recently came to our attention that there are no binary wheels for Python 3.9 available on PyPI yet [1]. While I don't know what it would take to build and publish them, I am humbly asking if you could do something about this in order to improve the situation for downstream users like outlined at https://github.com/ambianic/peerjs-python/issues/48.

As I recognized you are already using `cibuildwheel` within your GHA recipe, it might be feasible to expand the Python version into a matrix there?

https://github.com/PyAV-Org/PyAV/blob/5d73160e4af2a94b721d8d9fcb7658a9ade3cde7/.github/workflows/tests.yml#L210-L212

Thanks already for looking into this and keep up the spirit!

With kind regards,
Andreas.

[1] https://pypi.org/project/av/#files

cc @ivelin

**Comment by nestiank** [comment]
I use Python 3.9.1 for my AMD64 VS Code, and I recently succeeded `pip install av` but when importing av `ImportError: DLL load failed while importing _core` occurred. When installing av, pip used av-8.0.2-cp39-cp39-win_amd64.whl but I also see that there are no binary wheels for Python 3.9 available on PyPI yet, as @amotl kindly noted. May I ask whether should I downgrade Python to 3.8, or is this error happening independently with my Python version?

**Comment by nestiank** [comment]
I am very curious about what actually av-8.0.2-cp39-cp39-win_amd64.whl is.

**Comment by amotl** [comment]
Dear Juyoung,

> I use Python 3.9.1 for my AMD64 VS Code, and I recently succeeded `pip install av` but when importing av `ImportError: DLL load failed while importing _core` occurred.

While that might feel like it work, the error message shows that the chances are high that the build process did not succeed (on your Windows machine?).

> May I ask whether should I downgrade Python to 3.8, or is this error happening independently with my Python version?

I believe you will be definitively be better off with Python 3.8, as there are corresponding `av-8.0.2-cp38-cp38-win32.whl` and `av-8.0.2-cp38-cp38-win_amd64.whl` packages on PyPI.

With kind regards,
Andreas.

**Comment by nestiank** [comment]
Dear Andreas,

Special thanks to your kind reply! Definitely will try that.

Best wishes,
Juyoung

**Comment by amotl** [comment]
Hi there,

I see that the release of PyAV 8.0.3, published on Jan 23, 2021, now offers binary wheels for Python 3.9. So, I am closing this. Thanks a stack!

With kind regards,
Andreas.

[1] https://pypi.org/project/av/#files

**Comment by jlaine** [comment]
Thanks for closing the issue @amotl I hadn't spotted it when I cut the release!
