### ISSUE TITLE
How do I use os.pipe() to feed data to an av container?

### ISSUE THREAD

**Issue by zhengwei-coding** [PyAV-Org/PyAV#738]
## Overview
Dear all, i am trying to use pyav to decode a local file with a customized format. I uses pipe's write-end to feed the data in while pipe's read-end file object to pass to av.open(file) for decoding. However, it seems av.open(read_pipe) always throw TypeError.

My code and actual behaver is as follow:
>>> import os, av      
>>> r, w = os.pipe()
>>> fr = os.fdopen(r, 'rb')
>>> fw = os.fdopen(w, 'wb')
>>> ct = av.open(fr) 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "av\container\core.pyx", line 354, in av.container.core.open
  File "av\container\core.pyx", line 117, in av.container.core.Container.__cinit__
TypeError: File's name attribute must be string-like.
>>>

I am wondering if it just doesn't support a file object with the name being a number (fdopen seems to return a file object which's name is the fd (type int instead of string) or i did anything wrong here...   

Thanks for the help!!

**Comment by zhengwei-coding** [comment]
Hi all, followed the traceback info, i found the code line 113 ~ 117 in av/container/core.pyx as below:
        if isinstance(file_, str):
            self.name = file_
        else:
            self.name = getattr(file_, 'name', '<none>')
            if not isinstance(self.name, str):
                raise TypeError("File's name attribute must be string-like.")
            self.file = file_

it seems that it will check if the name attribute is a type of string (normally it is). However, in case the file is opened with its file descriptor, the name will be assigned as its file descriptor which is an integer. 
I am wondering if this type check is necessary here or should contain the case with # at least. 
Any comment?

Cheers.

**Comment by jlaine** [comment]
I agree this check is overly restrictive, file-like objects don't necessarily have a name, for instance `io.BytesIO` has no name at all..

**Comment by farleylai** [comment]
Any follow-up plan to fix the issue?
The stdout from `subprocess.Popen(...)` also does not have the name of `str` but `int` implying it's from some fileno that should be general to accept.

**Comment by jlaine** [comment]
Sure, write a PR including unit tests.

**Comment by farleylai** [comment]
Got it. Will definitely consider that.
So far in the short term, the `name` property from a pipe may be modified by accessing the underlying `raw.__dict__` as follows:

```python
    proc = subprocess.Popen(['./cmd-to-run'], stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
    print('name=', proc.stdout.name, type(proc.stdout.name), file=sys.stderr)
    proc.stdout.raw.__dict__['name'] = str(proc.stdout.name)
    print('name=', proc.stdout.name, type(proc.stdout.name), file=sys.stderr)
```

This gives expected output:
```python
name= 4 <class 'int'>
name= 4 <class 'str'>
```

However, after that, pyav further checks if the file-like source is seekable which is typical not from pipes and raises the exception as follows: 

```sh
Traceback (most recent call last):
  File "av/container/pyio.pyx", line 59, in av.container.pyio.pyio_seek_gil
io.UnsupportedOperation: File or stream is not seekable.
```

Would this be the hard limitation to use pyav with pipes?

**Comment by jlaine** [comment]
Hi, I've put together PR #917 which should fix this issue, and adds an explicit test for this usecase. Would you mind trying it out?

**Comment by jlaine** [comment]
I merged this too fast, the test suite seems to hang.

**Comment by wqh17101** [comment]
That is a good idea that both reading and writing by pipe should be supported by PyAV. When you add this feature,please add some example and add to docs. @jlaine

**Comment by jlaine** [comment]
@wqh17101 Writing to a pipe is not going to work for most containers as they require a seekable output. I have however added a test which checks it fails with a sane message. If you do have an example of a container format which supports writing to a non-seekable output, I'd be happy to try it out.
