### ISSUE TITLE
munmap_chunk(): invalid pointer

### ISSUE THREAD

**Issue by LossNAN** [PyAV-Org/PyAV#740]
when useing container.close（）；
it seems container delete erro
`   
       
     while True:
        packet = next(container.demux(target_stream))
        for frame in ctx.decode(packet):
            data = {}
            if not frame_id % frame_interval:
                data['frame'] = frame
                data['rstp'] = video_path
                if frame_buffer.qsize() < 3:
                    frame_buffer.put(data)
            frame_id += 1
        if frame_id > 50:
            ctx.close()
            break
    container.close()`

get erro：
`munmap_chunk(): invalid pointer
Aborted`

**Comment by jlaine** [comment]
Would you have a complete (but minimal!) example to reproduce this please?

**Comment by danaki** [comment]
I'm getting this error too. My code looks like:
```
def decode_cuda(path, i):
    container = av.open(path)
#     for stream in container.streams:
#         print(stream.type, stream)

    upper = container.streams.video[0]
    lower = container.streams.video[1]

    ctx = av.Codec('hevc_cuvid', 'r').create()
    ctx.extradata = upper.codec_context.extradata

    for packet in container.demux(upper):
        print(ctx.decode(packet))        
        for frame in ctx.decode(packet):
            i -= 1
            #img = frame.to_image()
            #display(img)

            if i <= 0:
                print("break 1")
                break

        if i <= 0:
            print("break 2")
            break
            
    print("Finished")
```

Without ```ctx.extradata = upper.codec_context.extradata``` I'm getting no frames, with it it produces ```munmap_chunk(): invalid pointer``` and crashes the notebook.

**Comment by jlaine** [comment]
Could you please try this PR #756

**Comment by danaki** [comment]
That fixed the issue. Thank you. @LossNAN can you check your example too?

**Comment by jlaine** [comment]
I don't think this issue was originally related to #756, since extradata was not being touched.

**Comment by riaqn** [comment]
I'm actually still having this problem - I also used `h264_cuvid` and copied `extradata` from the original codeccontext.

**Comment by Shade5** [comment]
Added both fixes to https://github.com/Shade5/PyAV/tree/hwaccel-1x
