### ISSUE TITLE
Allow vtag to be set

### ISSUE THREAD

**Issue by iBobbyTS** [PyAV-Org/PyAV#741]
## Overview
In FFmpeg we're able too set vtag for a stream, for example hvc1 is a tag of HEVC, so that we can play with QuickTime Player on a Mac (QuickTime only plays HEVC streams with the vtag hvc1, but the default vtag of libx265 is hev1). 

## Existing FFmpeg API
I'm not familiar with the C API of FFmpeg, I can only tell the command line option that set the vtag. 
`ffmpeg -i input.mp4 -c:v libx265 -vtag hvc1 output.mov`
OR
`ffmpeg -i input.mp4 -c:v libx265 -tag:v hvc1 output.mov`

## Expected PyAV API
Like what setting pix_fmt is like. 
https://pyav.org/docs/stable/cookbook/numpy.html#generating-video

Example:
```
container = av.open('test.mov', mode='w')
stream = container.add_stream('libx265', rate=30)
stream.tag = 'hvc1'
```

## Versions

- OS: {{ e.g. macOS 11.2.1 }}
- PyAV runtime:
```
PyAV v8.0.3
git origin: git@github.com:PyAV-Org/PyAV
git commit: v8.0.3
library configuration: --disable-doc --disable-static --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libwavpack --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-shared --enable-version3 --enable-zlib --prefix=/tmp/vendor
library license: GPL version 3 or later
libavcodec     58. 91.100
libavdevice    58. 10.100
libavfilter     7. 85.100
libavformat    58. 45.100
libavutil      56. 51.100
libswresample   3.  7.100
libswscale      5.  7.100
```
- PyAV build:
`Installed from pip`
- FFmpeg:
`Installed from pip`

**Comment by mikelei8291** [comment]
This "tag" actually belongs to [`av.codec.context`](https://pyav.org/docs/stable/api/codec.html#module-av.codec.context). In FFmpeg, it is the member named `codec_tag` of [`struct AVCodecContext`](https://ffmpeg.org/doxygen/trunk/structAVCodecContext.html#a2c974557671dd459674b170c5e64d79a), and is [wrapped in PyAV](https://pyav.org/docs/stable/development/includes.html#c.PhonyNameDueToError.codec_tag).

However, this property is not exposed yet so you cannot set its value at the moment, but once it is exposed, you can compute the value of it as defined in [`common.h`](https://ffmpeg.org/doxygen/trunk/common_8h_source.html#l00478) of FFmpeg and set it.

The tag values for HEVC is defined in the array [`ff_codec_movvideo_tags[]` in `isom.c`](https://www.ffmpeg.org/doxygen/3.3/isom_8c_source.html#l00163), if you would like to reference them.

**Comment by iBobbyTS** [comment]
I just gave up pyav and start using the FFmpeg pipe, that's easier for me because I'm more familiar with the command line interface.

**Comment by mikelei8291** [comment]
Yeah, it's a pretty simple task that can be achieved with some shell scripting. PyAV probably isn't the best way to do it, but still, this can be a useful feature.
