### ISSUE TITLE
Encoding opencv frames to h264 codec to transfer and decoding back the frames afetr recieving.

### ISSUE THREAD

**Issue by arvindchandel** [PyAV-Org/PyAV#746]
Hi,
In my use case I am trying base 64 encoding for transferring the frames. I am looking for alternative for encoding it to h264. Is it possible using PyAv. Need a link for related example.

Thanks

**Comment by rizwanishaq** [comment]
@arvindchandel I tried this [example](https://github.com/PyAV-Org/PyAV/blob/main/examples/numpy/generate_video.py)
without success, I also have to encode bgr frames to h264 encoding for streaming, if you get some help do let me know.

**Comment by arvindchandel** [comment]
@rizwanishaq the example 'generate_video.py', it basically may encode the frames from video, i did run it successfully. I want to add code to retrieve the encoded frame.

**Comment by rizwanishaq** [comment]
@arvindchandel I don't know 
`for packet in stream.encode(frame):
        container.mux(packet)`
if the packet is the encoded frame???

**Comment by rizwanishaq** [comment]
@arvindchandel did you get any solution for your problem??

**Comment by arvindchandel** [comment]
@rizwanishaq not yet..still looking for it. will update you once found, if u get it, then share with me.

**Comment by jlaine** [comment]
Can you please be a bit more explicit about what you're trying to do, I honestly have no idea here?

**Comment by arvindchandel** [comment]
@jlaine to give you more idea, my purpose is to transfer the jpg frames to the server for which so far i encoded them using base 64 encoding using cv2.imencode() function. I want to compress it more so that i can reduce latency, for which i want to try some other encoding/codec like h264. Is there easy way to do this in python?

**Comment by jlaine** [comment]
I'm still confused here: video codecs (such as h264) don't independently encode individual frames. They encode a sequence of frames, and the efficiency comes from the fact they mostly encode the difference between frames.

If you are not familiar with manipulating video streams, sticking to jpeg may be your best option. I have no idea why you would want to apply base64 encoding though.

**Comment by arvindchandel** [comment]
@jlaine first, thanks for your quick replying. so let me give bit more clear idea. I am capturing RTSP feed continuously and then processing each frame and generating meta data for each frame like number of people, their positions in frame i.e bounding box etc. Now sending these meta data along with frame in kafka packet over the network to server, that's why i encoded the frames.
I feel base-64 is not that efficient because it consume more bandwidth and add delay in receiving frames.
Though its true i am not much familiar about encoding techniques, need your suggestion in this use case, what would be better option than base-64 to encode the frames. did you mention about jpeg encoding?

**Comment by rizwanishaq** [comment]
@arvindchandel 
Actually, I have the same problem as you have, I also sending images using base64 at moment, and want to to send h264 encoded frame instead of base64 instead... I am trying like, I am trying  [ffmpeg-python](https://github.com/kkroening/ffmpeg-python) as well, but without any success.

**Comment by jlaine** [comment]
OK, I'm going to close this as out-of-scope:

- As mentioned above, video codecs don't encode video frames independently so the concept of an "encoded frame" doesn't apply. If you want to compress individual images, JPEG is fine.

- The discussion about base64 is really not relevant here, it's just a textual (and therefore inefficient) representation of binary data used in contexts where only text is allowed. If you want to sent JPEG files to a server, just send the binary data over HTTP for example and you'll be fine.
