### ISSUE TITLE
Convert pydub.AudioSegment to AudioFrame

### ISSUE THREAD

**Issue by el07694** [PyAV-Org/PyAV#755]
I want to use aiortc which use av to make a peer-to-peer connection between a browser user and a python user.
The python user will send a real time audio radio program which will be maked by pydub.

I tried to make pyav audiofrmes.from_ndarray with no luck.

Any help?

**Comment by el07694** [comment]
https://github.com/aiortc/aiortc/issues/483

**Comment by jlaine** [comment]
A minimal snippet of code which just does what this issue is about would have been nice, but nevermind.
