### ISSUE TITLE
How many frames per packet?

### ISSUE THREAD

**Issue by AndreVallestero** [PyAV-Org/PyAV#757]
## Overview

How many frames can there be in any video packet? I'm trying to index video frames without decoding but I'm unsure as to how many frames can be in each packet. From my limited testing, I've only seen packets with 0 or 1 frames.

**Comment by jlaine** [comment]
This is really out of scope for PyAV, I think you'd be better served checking the FFmpeg documentation, PyAV just binds to its libraries.
