### ISSUE TITLE
File "av/video/frame.pyx", line 336, in av.video.frame.VideoFrame.from_ndarray AssertionError

### ISSUE THREAD

**Issue by Mohitkumaraian** [PyAV-Org/PyAV#763]
Hi, I'm not able to resolve the following error when I'm using VideoFrame.from_ndarray(img). Could anyone help me understand why this is happening and how to fix it??

**Comment by jlaine** [comment]
https://github.com/PyAV-Org/PyAV/blob/9ac05d9ac902d71ecb2fe80f04dcae454008378c/av/video/frame.pyx#L336

Your array has the wrong shape for rgb24 or bgr24.

`array = numpy.random.randint(0, 256, size=(480, 640, 3), dtype=numpy.uint8)`
