### ISSUE TITLE
frames out of sequence after about 2^20 frames

### ISSUE THREAD

**Issue by ksze** [PyAV-Org/PyAV#78]
We are recording some very long YUV422 video as H.264, in a .nut file by piping the raw pixel data into `ffmpeg`'s stdin, with `-preset superfast`.

The exact `ffmpeg` command line is this:

```
ffmpeg -f rawvideo -pix_fmt yuyv422 -s:v 1920x1080 -r 30 -i pipe:0 -c:v libx264 \
-preset superfast -pix_fmt yuv422p -r 30 very_long_h264_video.nut
```

And then we try to read the recording using PyAV, using the usual demux and decode loops:

```
import av

container = av.open('very_long_h264_video.nut')

count = 0
_break = False
prev_time_in_ms = 33 # I don't know why ffmpeg makes our video start at 66.6666... ms instead of 0

for packet in container.demux():
    for frame in packet.decode():
        count += 1
        if isinstance(frame, av.VideoFrame):
            frame_time_in_ms = int(round(frame.time * 1000))
            if (frame_time_in_ms - prev_time_in_ms) not in (33, 34):
                _break = True
                break
            prev_time_in_ms = frame_time_in_ms
    if _break:
        break

print 'count:', count
print 'prev_time_in_ms:', prev_time_in_ms
```

And this prints out:

```
count: 1048567
time: 34952233
```

Somehow, for the first approximately 2^20 frames (1048567 is not exactly 2^20, but it's suspiciously  close), the frame times are all properly sequential, with no jump or duplication. But then weird things start to happen after that many frames: the frame times start getting out of sequence, some frame times are duplicated, and some frame times would go totally missing - not that any `VideoFrame` object has a time of `None`, but I never see a `frame.time` of 57336.4 seconds in the sequence, while I see 57336.3666... once, 57336.4333... once, and 57336.4666. twice.

For perspective, 2^20 frames is about 9 hours, 42 minutes, and 32.5333333 seconds at 30 fps. So if you want to try to reproduce the problem, you may need a video that long.

Do you have any idea if this is a ffmpeg encoding bug, ffmpeg decoding bug, or PyAV bug?

For example, this is a sequence of frame.time, frame.dts, and frame.pts that I would get if I printed them out (the frame.time is converted and rounded to milliseconds by doing `int(round(frame.time * 1000))`):

```
57336100 3522723840 3522729984
57335866 3522727936 3522715648
57336166 3522729984 3522734080
57336200 3522734080 3522736128
57336233 3522732032 3522738176
57336000 3522736128 3522723840
57336300 3522738176 3522742272
57336333 3522742272 3522744320
57336366 3522740224 3522746368
57336133 3522744320 3522732032
57336433 3522746368 3522750464
57336466 3522750464 3522752512  <--
57336500 3522752512 3522754560
57336266 3522754560 3522740224
57336566 3522752512 3522758656
57336600 3522758656 3522760704
57336633 3522760704 3522762752
57336666 3522762752 3522764800
57336700 3522760704 3522766848
57336466 3522764800 3522752512  <-- Duplicate frame.time and frame.pts!!
57336766 3522766848 3522770944
57336800 3522770944 3522772992
57336833 3522768896 3522775040
57336600 3522772992 3522760704
57336900 3522775040 3522779136
57336933 3522779136 3522781184
57336966 3522777088 3522783232
57336733 3522781184 3522768896
57337033 3522783232 3522787328
57337066 3522787328 3522789376
```

And then 57336400 is nowhere to be found even if I kept demuxing and decoding.

**Comment by mikeboers** [comment]
You sure keep coming up with fun ways to cause problems.

My instinct is that it is a bug in ffmpeg somewhere. It could also be a precision issue in our various pts handling code. Can you tell us what the time_base is for this stream?

Okay, how to test this. Hopefully it is a bug only regarding the times, so that we can make something which generates a stream of tiny, constant frames. Could potentially use the new PythonIO support to dump straight from the encoder into the decoder. That sounds like an interesting tool to have anyways.

Then need to instrument the values coming out of ffmpeg that we turn into the various time attributes, and see if the problem is in them, or in how we handle them.

**Comment by ksze** [comment]
Here is the time base:
```
In [7]: container.streams[0].time_base
Out[7]: Fraction(1, 61440)
```

**Comment by mikeboers** [comment]
What I've been trying is, in one terminal:

~~~
mkfifo pipe.nut
ffmpeg -f rawvideo -pix_fmt yuyv422 -s:v 1920x1080 -r 30 -i /dev/zero -c:v libx264 \
    -preset superfast -pix_fmt yuv422p -r 30 -f nut pipe:1 >> pipe.nut
~~~

...and your script in the other, reading from that pipe.

It is taking me 65 minutes to get to the right frame; lets wait and see what it does.

**Comment by mikeboers** [comment]
Hooray! I just got:

~~~
count: 1048566
prev_time_in_ms: 34952200
~~~

**Comment by mikeboers** [comment]
Clue #1: The size of the frame makes a difference: the same thing as above with a 4x3 frame does not stop at the same spot.

Clue #2: We can seek via `container.streams[0].seek(1048500 / 30.0)` and still have the problem.

**Comment by mikeboers** [comment]
Clue 3: Mine is failing with a pts of 2147448832, which is only 20480 from 2^31 and less than the time_base. Seems like a loss of precision somewhere.

**Comment by mikeboers** [comment]
Inspecting the pts and pkt_pts values right after coming out of avcodec_decode_video2, they match. The Cython code is treating them as 64bit. I have to believe it is in ffmpeg itself. Don't know if it is in the encoding or decoding phase though.
