### ISSUE TITLE
Can't set video stream time_base

### ISSUE THREAD

**Issue by hubeichenxing** [PyAV-Org/PyAV#784]
Hi, i have try to set video stream time_base with code bellow:
```
output = av.open("out.mp4", 'w')
stream = output.add_stream('h264', 24)
stream.pix_fmt = 'yuv420p'
stream.height = im_height
stream.width = im_width
stream.time_base = Fraction(1, 24)
print(stream.time_base)
print(stream.codec_context.time_base)
```
The command line output:
```
None
1/24
```
It means that the ```stream.time_base``` is not be assigned but ```stream.codec_context.time_base``` get it.
I use the container ```output``` to save a video, the ```time_base``` of packets is ```1/12288``` or other number, not ```1/24```.
I want to save a video that the ```time_base``` of ```AVStream``` set with me, how can i do ?

**Comment by gsakkis** [comment]
I'm hitting this bug too, for me the auto-set number is 1/12800. It's also reproducible in the [remuxing example](https://pyav.org/docs/develop/cookbook/basics.html?highlight=split#remuxing) where time_base is set to 1/1000 instead of 1/25 of the input file.
