### ISSUE TITLE
start time incorrect 

### ISSUE THREAD

**Issue by yim7** [PyAV-Org/PyAV#801]
## Overview

The start time read by pyav is inconsistent with ffprobe.

pyav
200
ffprobe
13640 

## Expected behavior

Same as ffprobe 

## Investigation
pyav sets the max_analyze_duration internally. It‘s not enough to read the start time.
![image](https://user-images.githubusercontent.com/12380332/127596576-6e4629a9-2cc1-48e2-8f3f-e053ffb80b81.png)

**Comment by jlaine** [comment]
@mikeboers any idea why we set `max_analyze_duration` ourselves? AFAICT libavformat already tries to set a sane default, which is format-dependent.

**Comment by mikeboers** [comment]
I do not. Blow it up?
