### ISSUE TITLE
How do I pass the protocol whitelist option to PyAV?

### ISSUE THREAD

**Issue by dcordb** [PyAV-Org/PyAV#806]
I'm trying to open a SDB file, that comes from a stream RTP. To do this with ffplay I have to pass the following flag: `-protocol_whilelist file,rtp,udp`, if not I get the following from ffmpeg and by extension from PyAV: `Protocol 'rtp' not on whitelist 'file,crypto,data'`.

How can I pass this to PyAV?

### More context

For example, OpenCV has a environment variable that allows to set flags like this:

```python
os.environ['OPENCV_FFMPEG_CAPTURE_OPTIONS'] = 'protocol_whitelist;file,rtp,udp'
```

**Comment by quentin-dietz** [comment]
I have had luck passing it as follows:
`av.open("stream.sdp",  options={"protocol_whitelist":"file,udp,rtp"})`

**Comment by dcordb** [comment]
Thank you it works! I'll close this.
