### ISSUE TITLE
Decoding HEVC raising error

### ISSUE THREAD

**Issue by shuoxinma4** [PyAV-Org/PyAV#813]
I'm using pip-provided PyAv 8.0.3 in Python 3.7.9 on Windows 10 to demux/decode some HEVC videos recorded through LAN cams. 
The first thing I noticed is that even with the same FFMpeg Binaries, PyAv yields different demuxed binary data than Nvidia's PyNvCodec-wrapped ffmpeg, even though both used default config and the PyAv-demuxed slices can be decoded by PyNvCodec. 
My problems is that PyAv raises error during decoding certain HEVC streams while PyNvCodec decode the whole stream fine, and the error pops at a different frame each time. Using PyAv to demux and PyNvCodec to decode cause the PyNvCodec to raise exception as well.
I have attached the trouble-causing stream in the link. 
My decoding programe is simply

decoder = av.open(inputStreamFilename, format='hevc', mode='r', timeout=0)
for i, frame in enumerate(decoder.decode()):
    # error on i=226, 280, 381, 305 among others
    # File "av\container\core.pyx", line 258, in av.container.core.Container.err_check
    # av.error.ExitError: [Errno 1414092869] Immediate exit requested
    print('Good until ',i)

Additional info
------
[With python -m av --version]
---------------
PyAV v8.0.3
git origin: git@github.com:PyAV-Org/PyAV
git commit: v8.0.3
library configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --enable-librav1e --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
library license: GPL version 3 or later
libavcodec     58. 91.100
libavdevice    58. 10.100
libavfilter     7. 85.100
libavformat    58. 45.100
libavutil      56. 51.100
libswresample   3.  7.100
libswscale      5.  7.100
------------------------------------------------------------------

No setup.py and ffmpeg.exe installed.

Much appreciated.

**Comment by jlaine** [comment]
Looks like an upstream issue, I have no idea what we can do here.
