### ISSUE TITLE
Make maintainer status clearer

### ISSUE THREAD

**Issue by riaqn** [PyAV-Org/PyAV#819]
- The latest commit is 7 months ago
- maintainers not replying to any issue for over a month
- several PR that I really need is not merged, with no reason given.

If the maintainers find themselves occupied by other things, it might be beneficial for the community if they can transfer the project to someone with more time to devote to the project; at least say so in the README so people who are interested can take over.  Currently we have an enthusiastic community and a dead project.

**Comment by Nitaym** [comment]
Hi @mikeboers,

Thanks for clearing up the status. This project is awesome, it really fills a void around video processing python in general. Kudos on that.

There are numerous companies relying on ffmpeg libraries as their video backend, so I believe finding someone to maintain or "sponsor" this project wouldn't be too difficult.

Could you describe what's the process of adding code to this repo? 
The av libraries support a trillion features with video, audio, data, images and more, making it a beast to test - What is your verification methods of new PRs?

**Comment by Queuecumber** [comment]
> There are numerous companies relying on ffmpeg libraries as their video backend, so I believe finding someone to maintain or "sponsor" this project wouldn't be too difficult.

 I agree with this, since torchvision depends on pyav (fairly heavily I think) I and facebook is pretty active in open source I could see them helping to maintain this

**Comment by jlaine** [comment]
It would be awesome to have some additional eyeballs and hands to help out. Everytime I have some spare time and want to get back on top of things I:

- discover something broke with CI or packaging. Currently the main holdup for new releases is that our source for ffmpeg binaries for Windows is gone (see pyav-ffmpeg). We probably need to do the same as for Linux / OS X and build our own so this doesn't happen again

- start looking at the open issues and get depressed by their sheer number. We need help triaging issues, and possibly closing those which are requests for help if we don't have the bandwidth to handle them

**Comment by jlaine** [comment]
OK, apparently this was a "hit-and-run" type of issue, not an actual offer for help, closing.

**Comment by riaqn** [comment]
I'm seeing some of the PR I cared about slowly being merged, so this issue is no longer relevant (at least for me).

However, I find your understanding of issues interesting - aren't issues simply about reporting existing problem with the project? Whether or not I'm willing to spend time to fix it is not relevant. If the reported problem exists, then the issue is valid.

**Comment by jlaine** [comment]
As far a I'm concerned the issue has been answered: you asked about the maintainer status and got answers from both maintainers.

If someone wants to step up and provide help triaging issues / reviewing PRs, they are very welcome to and I'll be happy to engage with her/him in a new discussion.
