### ISSUE TITLE
How to extract the audio frame?

### ISSUE THREAD

**Issue by ForawardStar** [PyAV-Org/PyAV#823]
**IMPORTANT:** Be sure to replace all template sections {{ like this }} or your issue may be discarded.

## Overview

How to extract the audio frames and save them in the disk, which can be loaded off-line if needed without extracting the audio frames from a video online every time. 

## Expected behavior

I hope one can provide a demo code for solving my question.

## Actual behavior

I have carefully read the document of PyAV, but I fail to find anything about saving and loading audio frames in an off-line fashion.

**Comment by jlaine** [comment]
I'm sorry but we cannot answer user support requests in the issue tracker, try discussion or gitter
