### ISSUE TITLE
Support conversion of NV12 frames into numpy array

### ISSUE THREAD

**Issue by prabhat00155** [PyAV-Org/PyAV#837]
## Overview

Add support for conversion of NV12 frames into numpy array. Currently, I am able to convert yuv420 frames to nv12 but can't access these frames using [`to_ndarray()`](https://github.com/PyAV-Org/PyAV/blob/9ac05d9ac902d71ecb2fe80f04dcae454008378c/av/video/frame.pyx#L240). I don't know if there is any other way to access these frames.

```
with av.open(path) as container:   
    for av_frame in container.decode(container.streams.video[0]):
        print(av_frame.reformat(format=av.VideoFormat('nv12')).to_ndarray())
```
```
ValueError: Conversion to numpy array with format `nv12` is not yet supported
```

## Desired Behavior

Should convert the frames into numpy array.

## Example API

```
with av.open(path) as container:   
    for av_frame in container.decode(container.streams.video[0]):
        print(av_frame.reformat(format=av.VideoFormat('nv12')).to_ndarray())
```

This should print the frames.

## Additional context

I have implemented a decoder which outputs nv12 frames and am looking for a way to verify the results.

**Comment by jlaine** [comment]
A PR is welcome, otherwise this is going nowhere

**Comment by jlaine** [comment]
I'm closing this issue, feel free to submit a PR when you have the time.
