### ISSUE TITLE
The number of frames this stream contains return 0?

### ISSUE THREAD

**Issue by dourcer** [PyAV-Org/PyAV#869]
container = av.open('/source/d3/encode_optim/hdcctv1/20201107/hdcctv1_20201107_05891.ts')
fps = float(container.streams.video[0].average_rate)
frames_length = container.streams.video[0].frames

frames_length  is 0?

howerver I use 
ffprobe -v error -count_frames -select_streams v:0 -show_entries stream=nb_read_frames -of default=nokey=1:noprint_wrappers=1 /source/d3/encode_optim/hdcctv1/20201107/hdcctv1_20201107_05891.ts

it is have result: 125
why?  Is there any other way to get it right frames_length  ?

**Comment by jlaine** [comment]
Please reproduce this with a publicly available file, there isn't much I can do with the name of your mystery video.
