### ISSUE TITLE
VideoFrame.to_image() doesn't work properly if width/height is specified

### ISSUE THREAD

**Issue by animetosho** [PyAV-Org/PyAV#878]
## Overview

`VideoFrame.to_image()` permits `width` and `height` parameters, according to documentation, however, if specified, they cause issues.

## Expected behavior

Either width/height is not supported in `to_image`, or it resizes the frame to specified dimensions.

## Actual behavior

If the width/height is smaller than original dimensions, a runtime error (`ValueError: not enough image data`) is thrown. If it's larger, it resizes, but doesn't change the image's dimensions, giving messed up output.

## Investigation

The `to_image` function uses [the frame's original dimensions](https://github.com/PyAV-Org/PyAV/blob/95475cc19e5e43b56225ae00e253adbaf5d3a35d/av/video/frame.pyx#L236) when constructing the image, as opposed to the after-reformatted dimensions.

(it may also be worth checking the other functions which pass the parameters onto `reformat` for similar issues)

## Versions

- PyAV runtime: 8.1.0

**Comment by jlaine** [comment]
This is a good catch, thanks! I'm wondering whether it even makes sense to accept additional keyword arguments as you can already transform the image yourself by explicitly calling `reformat`.

**Comment by animetosho** [comment]
Using `reformat` is what I'm doing, as PyAV [provides a shortcut](https://github.com/PyAV-Org/PyAV/blob/6443f55e7d07948a93cc03f417e3cb66227fd6bf/av/video/reformatter.pyx#L102-L109) when doing a second `reformat` (that `to_image` always requires).

I suppose it depends on whether you want users to be aware of that shortcut being present. Alternatively, if PyAV is mostly meant to be a wrapper to libav, one could also say that it should be close to the original interface.
