### ISSUE TITLE
ffmepg v5 has arrived (with some removals)

### ISSUE THREAD

**Issue by systemcrash** [PyAV-Org/PyAV#883]
The release note mentions `the entire libavresample library was removed,...`. Does pyav use or rely on this?

https://pyav.org/docs/8.0.1/api/audio.html#module-av.audio.resampler

Are these two unrelated/unconnected?

**Comment by jonassmedegaard** [comment]
ffmpeg v5 is available in Debian experimental, in case that is helpful.

The Debian ffmpeg package maintainers have filed a bugreport to track PyAV linking against ffmpeg v5: https://bugs.debian.org/1004776

**Comment by jlaine** [comment]
Let's track this in #817
