### ISSUE TITLE
Release new docs?

### ISSUE THREAD

**Issue by wqh17101** [PyAV-Org/PyAV#913]
## Overview

The latest doc is 8.0.2. But the version now is 9.0.2.
![image](https://user-images.githubusercontent.com/26429138/159826829-f1a8b2f8-e040-4b12-87cb-5bc1d32114f2.png)
 

## Expected behavior

Update doc  when released

**Comment by jlaine** [comment]
@mikeboers

**Comment by mikeboers** [comment]
I'm happy to either (1) upload a tarball of docs if someone can give it to me, or (2) point the domain elsewhere if there is a nice alternative. (or 3 build it myself if it now builds cleanly)

Once upon a time it was on Read The Docs, but it got too hard to build. Then it was on GitHub Pages, but I wanted to retain history.

**Comment by jlaine** [comment]
Hi Mike! Regardless of the hosting option, I have never even been able to build the docs locally, what should I be running ?

**Comment by mikeboers** [comment]
I can't build right now due to API changes. On Ubuntu with a clean PyAV it should be:

```
apt install doxygen # To generate the FFmpeg doxygen links
. scripts/activate.sh
./scripts/build-deps
make
make docs
```

**Comment by mikeboers** [comment]
The issue appears in the current Sphinx. I rolled back a bit: `pip install -U sphinx==0.4.3` and then I could `make docs`.

I just uploaded that to https://pyav.org/docs/develop/

**Comment by jlaine** [comment]
Very cool! Do we also want a "stable" release for 9.0.x ?

**Comment by jlaine** [comment]
I'm also seeing the following error:

```
Parsing Cython source for references...
    CompilerCrash in av/enum.pyx
        
Error compiling Cython file:
------------------------------------------------------------
...

    def __set__(self, inst, value):
        item = self.enum.get(value)
        self.fset(inst, item.value)

    def flag_property(self, name, doc=None):
   ^
------------------------------------------------------------

av.enum:353:4: Compiler crash in Visitor

ModuleNode.body = StatListNode(av.enum:12:0)
StatListNode.stats[9] = CClassDefNode(av.enum:325:5,
    as_name = 'EnumProperty',
    class_name = 'EnumProperty',
    module_name = '',
    visibility = 'private')
CClassDefNode.body = StatListNode(av.enum:327:4)
StatListNode.stats[8] = DefNode(av.enum:353:4,
    modifiers = [...]/0,
    name = 'flag_property',
    num_required_args = 2,
    outer_attrs = [...]/2,
    py_wrapper_required = True,
    reqd_kw_flags_cname = '0')

Compiler crash traceback from this point on:
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "/home/sharky/Development/pyav-org/PyAV/docs/development/includes.py", line 89, in visit_DefNode
    self.state.pop('function')
KeyError: 'function'
    CompileError in av/container/core.pxd
```

**Comment by mikeboers** [comment]
Just deployed a 9.0.2 and promoted it to stable.

**Comment by jlaine** [comment]
Awesome thanks @mikeboers ! I landed the fixes you suggested and a few others, so the next release should be less painful to build.

Any idea about the custom visitor crash? By the way why do we need this code?

Could you also provide some explanation about what we are doing with Doxygen?

**Comment by papr** [comment]
Hi! I just wanted to revive this issue as the docs page needs an update for the 10.0 release.

In terms of deployment and hosting, I have very good experience with releasing documentation via https://readthedocs.org/ They also support setting up custom domains. One would need to ensure that the docs build via a direct sphinx call, e.g. `python -m sphinx -W --keep-going <docs folder> <output folder>`.

**Comment by papr** [comment]
It also looks like the GA is building docs already. https://github.com/PyAV-Org/PyAV/actions/runs/3268253133/jobs/5374897596

Auto-deployment is probably just a matter of
1. Setting up rsync credenctials in the repository secrets settings
1. Uploading the built docs using https://github.com/actions/upload-artifact#upload-an-entire-directory
1. Creating an additional step that
    - depends on the `publish` steps
    - uses https://github.com/actions/download-artifact to download the built docs
    - runs `make upload`

**Comment by jlaine** [comment]
I don't have any access to the pyav.org domain at all, only @mikeboers does..

**Comment by mikeboers** [comment]
If @jlaine would be entertained to setup something with RTD or whatever, I'd be keen to point the domain elsewhere. I could also look into giving @jlaine access to that server.

**Comment by jlaine** [comment]
Fair enough, I'll give RTD a try :)

**Comment by papr** [comment]
Note, that (if I understood everything correctly) using rtd comes with two main challenges:
1. Rtd will attempt to build the module in order to run sphinx' auto doc functionality.
2. One would need to find a way to run doxygen to keep the ffmpeg reference links
