### ISSUE TITLE
Something like providing a binding to ffmpeg with gpu acceleration.

### ISSUE THREAD

**Issue by wqh17101** [PyAV-Org/PyAV#960]
## Overview

As it can use gpu to decode and do some scaling operation, we can add a switch to use gpu on the users's env to accelerate.

By the way, ffmpeg with gpu also provides cpu ablities.

## Existing FFmpeg API

https://docs.nvidia.com/video-technologies/video-codec-sdk/ffmpeg-with-nvidia-gpu/

## Expected PyAV API
for gpu
```
decode(device="GPU:0")
```
for cpu
```
decode(device="cpu")
```

## Investigation

(https://docs.nvidia.com/video-technologies/video-codec-sdk/ffmpeg-with-nvidia-gpu/

## Reproduction

{{ Steps to reproduce the behavior. If the problem is media specific, include a link to it. Only send media that you have the rights to. }}

## Versions

- FFmpeg:
```
./configure --prefix=/usr/local/ffmpeg --enable-cuda-nvcc --enable-cuvid --enable-shared --enable-nvenc --enable-shared --extra-libs=-lpthread --extra-libs=-lm --enable-gpl --enable-libx264 --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64 --enable-nonfree
```

## Additional context

{{ Add any other context about the problem here. }}

**Comment by jlaine** [comment]
As stated in the README, hardware acceleration is out of scope unless someone steps up to add support in our binary wheels *including tests*.
