### ISSUE TITLE
Using openh264 to replace x264 in ffmpeg as default

### ISSUE THREAD

**Issue by wqh17101** [PyAV-Org/PyAV#965]
## Overview

For x264 is GPL license,which will make the project using it become GPL license.
It is better to use openh264(BSD License) to replace x264 in ffmpeg.

**Comment by wqh17101** [comment]
Only process isolation can use GPL component without make the source project GPL.
Such as using it by command line.
So check whether pyav affected by this .
Without process isolation, we should not use GPL component .

**Comment by jlaine** [comment]
I think this is a duplicate of #805
